### ISSUE TITLE
How to import data from a stored procedure ?

### ISSUE THREAD

**Issue by vincentvanderwalt** [jprante/elasticsearch-jdbc#144]
I currently import data by reading a table and also some views from SQL Server. 

However I'm having to do some complex calculations before loading the data into Elastic search. 

Is there a way to pull data from the results of a stored procedure ?

Thanks and great plugin by the way.

Vinny

**Comment by kavurupavan** [comment]
bin=/home/pavan/Desktop/elasticsearch-jdbc-2.3.1.0/bin
lib=/home/pavan/Desktop/elasticsearch-jdbc-2.3.1.0/lib
echo ' {
    "jdbc" : {
        "strategy" : "oneshot",
        "driver": "org.postgresql.Driver",
        "url" : "jdbc:postgresql://127.0.0.1:5432/10kinfo_data",
        "user" : "b2g_mns",
        "password" : "b2gmns",
        "index" : "my_jdbc_river10",
        "type" : "my_jdbc_river10",
        "statement" : "{exec  onematchpage_photo}",
        "callable" : true,
        "fetchsize" : 1000
      }
    
}' | java \
       -cp "/home/pavan/Desktop/elasticsearch-jdbc-2.3.1.0/lib/*" \
       -Dlog4j.configurationFile=/home/pavan/Desktop/elasticsearch-jdbc-2.3.1.0/bin/log4j2.xml \
       org.xbib.tools.Runner \
       org.xbib.tools.JDBCImporter

Error : no sql found .. Please help me..Thanks in advance.

**Comment by jprante** [comment]
Please use
```
"jdbc" : {
    "url" : "jdbc:postgresql://127.0.0.1:5432/10kinfo_data",
    "user" : "b2g_mns",
    "password" : "b2gmns",
    "index" : "my_jdbc_river10",
    "type" : "my_jdbc_river10",
    "sql" : {
        "statement" : "{exec onematchpage_photo}",
        "callable" : true
    }
}
```

**Comment by kavurupavan** [comment]
Thanks sir.. I will check and inform sir..

**Comment by kavurupavan** [comment]
Error : [ERROR][importer.jdbc.context.standard][pool-3-thread-1] at fetch:
org.postgresql.util.PSQLException: ERROR: relation "onematchpage_photo"
does not exist

I have input parameters for stored procedure *onematchpage_photo *having 3
input parameters.

**Comment by kavurupavan** [comment]
Hi sir..
without giving input parameter can execute stored procedure in elastic search. Please help me. Thanks in advance...

Ex :
echo ' {
    "type": "jdbc",        
    "jdbc": {
      "driver": "org.postgresql.Driver",
      "url" : "jdbc:postgresql://127.0.0.1:5432/10kinfo_data",
      "user" : "b2g_mns",
      "password" : "b2gmns",
      "poll": "10m",
      "strategy": "simple",
      "index" : "people2",
      "type"  :  "company2",
      "autocommit" : true,
      "sql" : [
            {
                "callable" : true,
                "statement" : "{call sp_ds_onematchpage_sgst_photo(?::varchar, ?::bigint, ?::bigint, ?::int)}",
                "parameter" : [
                     "DS", 201407655,14316,2
                ]
              }
        ]
    }
}

**Comment by Rahul96553** [comment]
how to import single/multiple SQL stored procedure in Elastic search.?
