### ISSUE TITLE
River hangs when executing a stored procedure

### ISSUE THREAD

**Issue by futurechan** [jprante/elasticsearch-jdbc#219]
I have 3181197 records to import into Elasticsearch

My river configuration is

```
 {
    "type": "jdbc",        
    "jdbc": {
      "driver": "com.microsoft.sqlserver.jdbc.SQLServerDriver",
      "url": "jdbc:sqlserver://instance;databaseName=db",
      "user": "user",
      "password": "password",
      "poll": "10m",
      "strategy": "simple",
      "index" : "people",
      "autocommit" : true,
      "sql": "Exec river_getData",
      "callable":true
    }
}
```

The last line in my console is

```
[2014-04-11 14:07:52,509][INFO ][org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverMouth] bulk [32201] success [99 items] [7174ms]
```

And the river stops with about 1865291 records imported.

**Comment by kavurupavan** [comment]
bin=/home/pavan/Desktop/elasticsearch-jdbc-2.3.1.0/bin
lib=/home/pavan/Desktop/elasticsearch-jdbc-2.3.1.0/lib
echo ' {
    "jdbc" : {
        "driver": "org.postgresql.Driver",
        "url" : "jdbc:postgresql://localhost:5432/testdb",
        "user" : "sqoop",
        "password" : "sqoop",
        "sql" : [
            {
                "callable" : true,
                "statement" : "{call GET_SUPPLIER_OF_COFFEE(?, ?)}",
               "parameter" : [
                     "Colombian"
                ],
                "register" : {
                     "supplierName" : { "pos" : 2, "type" : "varchar"}
                }
                
            }
        ],
        "index" : "my_jdbc_river5",
        "type" : "my_jdbc_river5"
    }
}' | java \
       -cp "/home/pavan/Desktop/elasticsearch-jdbc-2.3.1.0/lib/*" \
       -Dlog4j.configurationFile=/home/pavan/Desktop/elasticsearch-jdbc-2.3.1.0/bin/log4j2.xml \
       org.xbib.tools.Runner \
       org.xbib.tools.JDBCImporter

[ERROR][importer.jdbc.context.standard][pool-3-thread-1] at fetch: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
