### ISSUE TITLE
Error: Could not find or load main class org.xbib.elasticsearch.plugin.feeder.Runner

### ISSUE THREAD

**Issue by jbwl** [jprante/elasticsearch-jdbc#274]
This is on Ubuntu 14.04 using ES 1.2.1 (installed with dpkg of the deb package) and the jdbc-river plugin 1.2.1.1 (installed with plugin/install)

I am trying to set up a feeder (first time to try it), using the mysql example as a template. When I try to run the script, I get the following error:

Error: Could not find or load main class org.xbib.elasticsearch.plugin.feeder.Runner

I put the script into the same path as the example script. I've checked for the classes but they are not in the path, in fact they are not on the system. Am I missing some libraries? How do I get them on my system?

As a second question, would like to be able to put my feeder shell script in any folder on my system, and supply the right path to the libraries.

**Comment by monotek** [comment]
does not work for me too.
Ubuntu 14.04
Elasticsearch 1.4.1
elasticsearch-river-jdbc-1.0.0.RC1.2

**Comment by aakshaye** [comment]
I have the same issue mentioned by jbwl 
Ubuntu 14.04
Elasticsearch 1.6.0

Am I doing someting wrong?
