### ISSUE TITLE
ES node is broken after removing the plugin files

### ISSUE THREAD

**Issue by ArtyomBaranovskiy** [jprante/elasticsearch-jdbc#439]
Hello,

Today I faced another strange issue with JDBC river:
to try feeder configuration, I removed the JDBC plugin files from ES node;
after that the node was never able to connect to the cluster.
On the other hand, once I restore the plugin files, the node successfully join cluster.
Additionally, if I put a different plugin version files, then the node is broken again (so only restoring 1.4.0.4 repairs it).

The issue is 100% reproducible in my cluster (Windows machines, 2 dedicated masters, 2 data nodes, unicast discovery).

ES reports the following in the log:
`[***][DEBUG][cluster.service] [***] processing [finalize_join ([***-master][dFmi_1YIQUWsreI2uS4ABA][***][inet[/***:9300]]{data=false, master=true})]: execute`
`[***][DEBUG][discovery.zen] [***] no master node is set, despite of join request completing. retrying pings.`

Could you please give me a hint how to remove JDBC river plugin properly?
NOTE: I want to remove it from only one node in cluster, all the others should remain working.

**Comment by jprante** [comment]
The JDBC plugin adds custom metadata to the cluster state. When one node get the JDBC plugin files removed, the node does no longer accept the master metadata from the cluster - what exactly happens, I do not know. This is unintended behavior. I am still investigating how to fix this. In the meantime, please keep all nodes with the JDBC plugin installed. This should not be a disadvantage.

**Comment by ArtyomBaranovskiy** [comment]
@jprante,
I want to run JDBC plugin in feeder mode (or on a separate non-data ES node) due to the following reason:
previously we had fielddatasize set to unbounded and quite small JVM heap settings, so once the data size increased, the ES started to fail with out of memory exceptions.
At the same time, JDBC plugin also experienced out of memory error and never started again.
I'm still investigating whether it is an ES issue or JDBC river issue, but anyway this makes me think that having JDBC plugin running in a separate process is more reasonable.

BTW, as I already mentioned, if I put 1.4.0.8 jar instead of 1.4.0.4, then the node breaks again.
So I will not be able to upgrade even if you provide a fix.
Perhaps I will need to fix the cluster state manually, do you think it is possible?

**Comment by jprante** [comment]
You can not mix nodes with and without JDBC plugin installed. To prevent JDBC plugin from getting installed, you must remove it from all nodes and restart the whole cluster so the master node does not use the JDBC plugin custom cluster metadata.

Please be patient for a fix for the JDBC plugin state management.
