### ISSUE TITLE
Can't setup incremental updates for table

### ISSUE THREAD

**Issue by aeryaguzov** [jprante/elasticsearch-jdbc#448]
I've installed jdbc as plugin(latest version 1.4.0.9) to index mysql table using readme.
1. It seems that schedule parameter does not work as expected.

On first start river plugin execute query and index data as expected (I see record about this in elasticsearch log file). 

I've setup schedule : "0 0-59 0-23 ? \* *", so I expect that every minute I should see new log about river execution, but nothing happened. I've also executed curl on _river/jdbc/{name}/_state and see that never happened (counter:1, and all dates are setup for first run).

Does schedule parameter works with jdbc installed as plugin and how I can test it?
1. It seems that $river.state.last_active_begin does not work as expected

I've tailed mysql query log and see that on every query execution this parameter equals current timestamp, so I have not get any records from table since last river run.

Is there some parameter that actually is a last river run timestamp?

**Comment by sawickil** [comment]
"schedule" : "0 * * * * ?"

yep, I also noticed that $river.state.last_active_begin did not work as expected. There are some other issues reported about this.
