### ISSUE TITLE
JDBC Driver preventing elasticsearch service from restarting

### ISSUE THREAD

**Issue by buinauskasevaldas** [jprante/elasticsearch-jdbc#476]
Hi Jörg,

i've faced issue when trying to restart Elasticsearch service in Windows 7 (x64) machine. Everything works fine if there are no plugins, however with JDBC plugin I'm unable to restart service and this needs to be done manually (kill process, start service)
This is the error I'm getting after trying to restart service.

![image](https://cloud.githubusercontent.com/assets/7301441/6366756/4dbae42e-bcd3-11e4-9e0c-b67c3cf24b89.png)

I've set service logging to Debug level, however it doesn't produce any errors at all.
[2015-02-25 09:49:07,831][INFO ][node                     ] [Derrick Slegers Speed] stopping ...
[2015-02-25 09:49:07,838][INFO ][river.jdbc.JDBCRiver     ] river closed [jdbc/products]
[2015-02-25 09:49:07,868][INFO ][node                     ] [Derrick Slegers Speed] stopped
[2015-02-25 09:49:07,868][INFO ][node                     ] [Derrick Slegers Speed] closing ...
[2015-02-25 09:49:07,872][INFO ][node                     ] [Derrick Slegers Speed] closed

That's it. Seem this is similar issue:
https://groups.google.com/forum/#!msg/elasticsearch/nzf4sUcf7n0/k5Bb9JkNLDYJ

Tried both jTDS and Propiertary MS Driver.

Thanks,
Evaldas.

**Comment by jprante** [comment]
Which JDBC plugin version is this?

**Comment by buinauskasevaldas** [comment]
Hi,

I'm using 1.4.0.10 version.

**Comment by jprante** [comment]
I can not check proprietary JDBC drivers, or Windows service, for bugs. 

Maybe the JDBC drivers have issues, I don't know.

**Comment by loganbhardy** [comment]
I've seen similar behavior on Linux. Elasticsearch 1.4.4, elasticsearch-river-jdbc-1.4.4.0.jar, sqljdbc41.jar. 

Rivers stop running on one of my four nodes. Removing and adding the river again will produce a _meta document but the _status document is missing. Restarting Elasticsearch fails on multiple attempts. I have to stop the process then start it separately. Once I've done this everything runs fine for a period of time. Days or weeks but eventually I end back up in this weird state. I can't find anything at all in the logs to note.

**Comment by jprante** [comment]
@loganbhardy please open a new issue and do not capture existing issues. This is a Windows issue I can not resolve.
