### ISSUE TITLE
Two records merging into same object inspite of different _id value

### ISSUE THREAD

**Issue by arunkoshi** [jprante/elasticsearch-jdbc#487]
I was trying out the latest Elasticsearch 1.4.4. along with the river plugin as we are planning to upgrade our existing elastic search from the 0.90.9 version.  

After loading data for some our databases, i noticed that two records were incorrectly combined into a single object in spite of having different _id values. This can be replicated using the following simple river request. 

River :
{
  "strategy": "simple",
  "bulk_size" : 2000,
  "max_bulk_requests" : 1,
  "threadpoolsize" : 1,
  "schedule": null,
  "type": "jdbc",
  "jdbc": {
    "url": "jdbc:sqlserver://DATABASE_IP;databaseName=DATABASE_NAME",
    "user": "USER_NAME",
    "password": "PASSWORD",
    "index": "my_index", 
    "sql": [
    {
    "statement" : "SELECT 'Employee' as _type, '12055T' as _id, '12055T' as EmployeeNumber
    UNION
    SELECT 'Employee' as _type, '120565' as _id, '120565' as EmployeeNumber"
    }
    
    ]
  }
}

Resulting Object:
{   "_index": "my_index",
    "_type": "Employee",
    "_id": "12055T",
    "_version": 1,
    "_score": 1,
    "_source": {
        "EmployeeNumber": ["12055T" , "120565" ]
    }
}

The two ids 12055T and 120565 generate the same hashcode (in PlainIndexableObject class) and hence are considered same by the equals() method. I am submitting a pull request with a fix to use the compareTo method instead of hashcode.

**Comment by jprante** [comment]
Thanks for the issue, yes, the hashcode is weak, I would appreciate any improvement on this.

**Comment by jprante** [comment]
I have committed a change of the hash function, be reusing tailored implementations from Apache Commons, and a test which shows the problem is fixed: https://github.com/jprante/elasticsearch-river-jdbc/commit/253059747f6394af3bcbf27875193e860d88e461

**Comment by arunkoshi** [comment]
Thanks so much!. I will try it out.
