### ISSUE TITLE
How to specifif mapping and analysis for a field what created by elasticsearch?

### ISSUE THREAD

**Issue by astrung** [jprante/elasticsearch-jdbc#525]
I have a index what created by elasticsearch-river.But in this index,i need specifif mapping and analysis for some field of this index.How can we do that?

**Comment by jprante** [comment]
You can create index beforehand, or you can use JDBC plugin parameter `index_settings` and `type_mapping`

**Comment by astrung** [comment]
We can create an index before create river??So if our mapping confict with MySQL column type,what happens??

**Comment by jprante** [comment]
I don't know - it depends. You can enable/disable dynamic mapping, or send wrong data, it will give a lot of errors then.
