### ISSUE TITLE
Oracle TIMESTAMP(6)  Conversion issues

### ISSUE THREAD

**Issue by qianglu1989** [jprante/elasticsearch-jdbc#533]
Dear:
I want from oracle conversion time to es!
the type is TIMESTAMP(6) 

 mapping
 "_timestamp" : {
            "enabled" : true,
            "path" : "OPER_TIME",
            "format" : "dateOptionalTime"
        },

The results 2015-02-02T11:53:36.887+08:00 

I want to change into a similar yyyy - MM - dd
What should I do?

**Comment by jprante** [comment]
I do not understand the question.  `2015-02-02T11:53:36.887+08:00` is a valid time, and has the required format `dateOptionalTime`

**Comment by qianglu1989** [comment]
I feel sad for my English!
my oracle time zone is systimestamp 
 
so,oracle Column value is 16-APR-15 03.09.44.634083 PM +08:00

and es  default format is "dateOptionalTime", 
as a result  2015-02-02T15:00:14.883+08:00
but,I want to formatting time fields to yyyy-MM-dd hh:mm:ss

What should I do? " timezone"  parameter? or.....

I tested a lot of ways, but didn't solve the problem, I need help

**Comment by jprante** [comment]
This is not related to JDBC plugin.

Elasticsearch expects UTC only. You have to convert to UTC in Oracle and format the result.

Example:

    SELECT to_char(from_tz(localtimestamp, 'Europe/Berlin') AT TIME ZONE 'UTC', 'yyyy-MM-dd hh24:mi:ss') as utc FROM dual;

**Comment by qianglu1989** [comment]
I tried this method
my config
curl -XPUT 'localhost:9200/_river/my_oracle_river/_meta' -d '{
    "type" : "jdbc",
   
    "jdbc" : {
        "url" : "jdbc:oracle:thin:@//10.16.10.54:1521/ebbc",
        "user" : "ebbc",
        "password" : "ebbc",
        "sql" : "select  to_char(OPER_TIME, 'yyyy-MM-dd hh:mm:dd') OPER_TIME_N,t.* from T_GNR_OPERATE_LIST t ORDER BY OPER_TIME_N DESC",
        "index" : "ebbc-operate",
        "type" : "operate",
        "schedule" : "30 * * ? * *",
        "connection_properties" : {
            "oracle.jdbc.TcpNoDelay" : false,
            "useFetchSizeWithLongColumn" : false,
            "oracle.net.CONNECT_TIMEOUT" : 10000,
            "oracle.jdbc.ReadTimeout" : 50000
        }
    }
}'
=====================================================================
 error logs
===================================================================
[1/4]: hh24:mi:ss) as utc  from  t_gnr_operate_list order by  OPER_TIME desc",
        "index" : "ebbc-operate",
        "type" : "operate",
        "schedule" : "30 * * ? * *",
        "connection_properties" : 
            "oracle.jdbc.TcpNoDelay" : false --> <stdout>
{"error":"MapperParsingException[failed to parse]; nested: JsonParseException[Unexpected end-of-input in VALUE_STRING\n at [Source: [B@f23fd26; line: 8, column: 346]]; ","status":400}--_curl_--hh24:mi:ss) as utc  from  t_gnr_operate_list order by  OPER_TIME desc",
        "index" : "ebbc-operate",
        "type" : "operate",
        "schedule" : "30 * * ? * *",
        "connection_properties" : 
            "oracle.jdbc.TcpNoDelay" : false
curl: (6) Couldn't resolve host 'hh24:mi:ss) as utc  from  t_gnr_operate_list order by  OPER_TIME desc",'

[2/4]: hh24:mi:ss) as utc  from  t_gnr_operate_list order by  OPER_TIME desc",
        "index" : "ebbc-operate",
        "type" : "operate",
        "schedule" : "30 * * ? * *",
        "connection_properties" : 
            "useFetchSizeWithLongColumn" : false --> <stdout>
--_curl_--hh24:mi:ss) as utc  from  t_gnr_operate_list order by  OPER_TIME desc",
        "index" : "ebbc-operate",
        "type" : "operate",
        "schedule" : "30 * * ? * *",
        "connection_properties" : 
            "useFetchSizeWithLongColumn" : false
curl: (6) Couldn't resolve host 'hh24:mi:ss) as utc  from  t_gnr_operate_list order by  OPER_TIME desc",'

[3/4]: hh24:mi:ss) as utc  from  t_gnr_operate_list order by  OPER_TIME desc",
        "index" : "ebbc-operate",
        "type" : "operate",
        "schedule" : "30 * * ? * *",
        "connection_properties" : 
            "oracle.net.CONNECT_TIMEOUT" : 10000 --> <stdout>
--_curl_--hh24:mi:ss) as utc  from  t_gnr_operate_list order by  OPER_TIME desc",
        "index" : "ebbc-operate",
        "type" : "operate",
        "schedule" : "30 * * ? * *",
        "connection_properties" : 
            "oracle.net.CONNECT_TIMEOUT" : 10000
curl: (6) Couldn't resolve host 'hh24:mi:ss) as utc  from  t_gnr_operate_list order by  OPER_TIME desc",'

[4/4]: hh24:mi:ss) as utc  from  t_gnr_operate_list order by  OPER_TIME desc",
        "index" : "ebbc-operate",
        "type" : "operate",
        "schedule" : "30 * * ? * *",
        "connection_properties" : 
            "oracle.jdbc.ReadTimeout" : 50000
         --> <stdout>
--_curl_--hh24:mi:ss) as utc  from  t_gnr_operate_list order by  OPER_TIME desc",
        "index" : "ebbc-operate",
        "type" : "operate",
        "schedule" : "30 * * ? * *",
        "connection_properties" : 
            "oracle.jdbc.ReadTimeout" : 50000
        
curl: (6) Couldn't resolve host 'hh24:mi:ss) as utc  from  t_gnr_operate_list order by  OPER_TIME desc",'

**Comment by jprante** [comment]
Please use correct escape syntax for apostrophes and quotes on your shell if using curl.

Apostrophe `'` is escaped by `'"'"'`

**Comment by qianglu1989** [comment]
I'm sorry, but I want to ask next how should I change
=================================================

curl -XPUT 'localhost:9200/_river/my_oracle_river/_meta' -d '{
    "type" : "jdbc",
   
    "jdbc" : {
        "url" : "jdbc:oracle:thin:@//10.16.10.54:1521/ebbc",
        "user" : "ebbc",
        "password" : "ebbc",
        "sql" : "select  to_char(OPER_TIME, 'yyyy-MM-dd hh:mm:dd') OPER_TIME_N,t.* from T_GNR_OPERATE_LIST t ORDER BY OPER_TIME_N DESC",
        "index" : "ebbc-operate",
        "type" : "operate",
        "schedule" : "30 * * ? * *",
        "connection_properties" : {
            "oracle.jdbc.TcpNoDelay" : false,
            "useFetchSizeWithLongColumn" : false,
            "oracle.net.CONNECT_TIMEOUT" : 10000,
            "oracle.jdbc.ReadTimeout" : 50000
        }
    }
}'

**Comment by qianglu1989** [comment]
Thank you very much for the support jprante a great god, for I bring trouble please understanding！

**Comment by qianglu1989** [comment]
Sorry i re-open it
Now, I've succeeded in synchronization time field
but,it type is 
"OPER_TIME_N": {
    "type": "string"
},
I think he should be

"OPER_TIME_N": {
    "type": "date"
},

f I set the mapping   "type": "date", data will not be synchronized

my config
=======================================
curl -XPUT 'localhost:9200/_river/my_oracle_river/_meta' -d '{
    "type" : "jdbc",
   
    "jdbc" : {
        "url" : "jdbc:oracle:thin:@//10.16.10.54:1521/ebbc",
        "user" : "ebbc",
        "password" : "ebbc",
        "sql" : "select  to_date(to_char(OPER_TIME,'"'"'yyyy-MM-dd hh24:mi:ss'"'"'),'"'"'yyyy-MM-dd hh24:mi:ss'"'"') OPER_TIME_N,t.* from T_GNR_OPERATE_LIST t ORDER BY OPER_TIME_N DESC",
        "index" : "ebbc-operate",
        "type" : "operate",
        "schedule" : "30 * * ? * *",
        "connection_properties" : {
            "oracle.jdbc.TcpNoDelay" : false,
            "useFetchSizeWithLongColumn" : false,
            "oracle.net.CONNECT_TIMEOUT" : 10000,
            "oracle.jdbc.ReadTimeout" : 50000
        }
    }
}'
