### ISSUE TITLE
Syntax SQL multiline with feeder and batch file?

### ISSUE THREAD

**Issue by d0lur1g** [jprante/elasticsearch-jdbc#537]
I success configure with yours advices.
With a simple line of sql, it's run.

But with multiline SQL, it's not run.

What is it the sql syntax with multiline?

    "jdbc" : {
        "url" : "url",
        "user" : "user",
        "password" : "password",
        "sql" :  "SELECT MBugs.id AS _id,
                MProjects.name AS Projet,
                MCategory.name AS Categorie,
                MBugs.summary AS Resume,
                CASE MBugs.status
                WHEN 90 THEN 'Fermé'",
                FROM mantis_bug_table MBugs
                INNER JOIN mantis_project_table MProjects ON MBugs.project_id = MProjects.id
                INNER JOIN mantis_user_table MUsers ON MBugs.reporter_id = MUsers.id
                INNER JOIN mantis_category_table MCategory ON MBugs.category_id = MCategory.id
                LEFT OUTER JOIN mantis_user_table MUsers2 ON MBugs.handler_id = MUsers2.id
                WHERE
                MBugs.project_id > 1100
                ORDER BY MProjects.name, MBugs.severity, MBugs.priority DESC"
        "treat_binary_as_string" : true,
        "index" : "yrdy",
        "type" : "feeder_test"
    }

And the error is : 

      {    "elasticsearch" : {         "cluster" : "elasticsearch",         "host" : "localhost",         "port" : 9300,         "type" : "jdbc",         "schedule" : "0 0-59 0-23 ? * *"    },    "jdbc" : {        "url" : "jdbc:mysql://a99mantis001.cdweb.biz:3306/mantis",        "user" : "user",        "password" : "user",        "sql" : "SELECT MBugs.id AS _id,
      'MProjects.name' is not recognized as an internal or external command,
      operable program or batch file.
      'MCategory.name' is not recognized as an internal or external command,
      operable program or batch file.
      'MBugs.summary' is not recognized as an internal or external command,
      operable program or batch file.
      'CASE' is not recognized as an internal or external command,
      operable program or batch file.
      'WHEN' is not recognized as an internal or external command,
      
      etc...

It's parse at line break.

**Comment by d0lur1g** [comment]
It works.
In fact, I put everything on a single line.
That does not like the indentation.

Thanks!

**Comment by L0rD59** [comment]
Can you close your issue ? thx

**Comment by d0lur1g** [comment]
Yes, you can close. thx.

**Comment by L0rD59** [comment]
I can't ! 

YOU must close.

thx

**Comment by d0lur1g** [comment]
ok
