### ISSUE TITLE
Feeders not supported in the new version ?

### ISSUE THREAD

**Issue by juanwolf** [jprante/elasticsearch-jdbc#572]
Hi,

I was looking for the feeder definition and I went surprised when I saw the Feeders feature has been removed for the version 1.6 (at least from the readme). 

Is there a new definition of it or it's deprecated ?

(Sorry if my question is silly, I'm new in this technology)

Thanks

**Comment by jprante** [comment]
The feeder was renamed to importer, functionality is the same.

**Comment by juanwolf** [comment]
Ok, thanks for the answer !
