### ISSUE TITLE
SSL=true in connection string has no effect

### ISSUE THREAD

**Issue by akobler** [jprante/elasticsearch-jdbc#578]
Hi all

I am using this es-jdbc component to pull data from a PostgreSQL server. I would really like to transfer my data over SSL. As a first try I configured the ES-jdbc as follows:

```
echo '
{
    "elasticsearch" : {
        "cluster" : "XXX",
        "host" : "localhost",
        "port" : 9300
    },
    "type" : "jdbc",
    "jdbc" : {
        "url": "jdbc:postgresql://XXX?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory",
        "user": "XXX",
        "password": "XXX",
        "index": "XXX",
        "type": "XXX",
        "sql" :  "select * from XXX"
    }
}
' | java -cp "${ES_HOME}/lib/*:${ES_HOME}/plugins/jdbc/*" org.xbib.elasticsearch.plugin.jdbc.feeder.Runner org.xbib.elasticsearch.plugin.jdbc.feeder.JDBCFeeder
```

As you can see I appended  `?ssl=true&sslfactory=...` to the url as a first try, to trigger jdbc establishing a SSL connection. (A further step would be client authentication with a certificate). Having a short look at Wireshork I see everything still as a raw TCP stream.

Has anybody already figured out how to force the ES-jdbc to use a SSL connection?

Thanks for sharing your ideas.

**Comment by jprante** [comment]
Can you try parameter `connection_properties`  with `"ssl" : "true"`?

See https://github.com/jprante/elasticsearch-jdbc#connection-properties-for-jdbc-driver

**Comment by akobler** [comment]
Thanks for this hint, I did not know this configuration possibility. Unfortunately There is still no effect with:

```
        "connection_properties": {
            "ssl": "true",
            "sslfactory": "org.postgresql.ssl.NonValidatingFactory"
        }
```

In the meantime I tried with the public certificate of the PostgreSQL system and get the following exception:
```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I am figuring out how to set the right parameters so that the java runtime can find that public certificate.

**Comment by jprante** [comment]
You need to import the certificate from Postgresql into a keystore and invoke the JDBC importer with `javax.net.ssl.trustStore` and `javax.net.ssl.trustStorePassword`, see

https://jdbc.postgresql.org/documentation/81/ssl-client.html

**Comment by mklaber** [comment]
@akobler adding `ssl` and `sslfactory` to the `url` parameter itself worked for me:

```
jdbc:postgresql://ec2-123-123-123-123.compute-1.amazonaws.com:1234/my_db?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
```

**Comment by akobler** [comment]
Sorry for my long delay. Now I could track it down and see that it is secured with the following connection string, as mentioned above.

```
jdbc:postgresql://ec2-123-123-123-123.compute-1.amazonaws.com:1234/my_db?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
```
