### ISSUE TITLE
Can some let know about the syntax

### ISSUE THREAD

**Issue by vaniaravinda** [jprante/elasticsearch-jdbc#588]
TITLE:"same old song and dance"^100 
		OR (
				TITLE:same~0.8 AND TITLE:old~0.8 AND TITLE:song~0.8 AND TITLE:and~0.8 AND TITLE:dance~0.8
		)^50 

Please explain about ^ & ~ in above query.

**Comment by jprante** [comment]
This is not an Elasticsearch JDBC issue.
