### ISSUE TITLE
NoNodeAvailableException

### ISSUE THREAD

**Issue by sandesh2014** [jprante/elasticsearch-jdbc#596]
There was an issue running JDBC Importer. Issue being: "org.elasticsearch.client.transport.NoNodeAvailableException: no cluster nodes available, check settings"

Can someone help me out. 

Below is the script:

export ES_HOME=/usr/share/elasticsearch
bin=/opt/elasticsearch-jdbc-1.6.0.0/bin
lib=/opt/elasticsearch-jdbc-1.6.0.0/lib

echo '
{

    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:sqlserver://192.168.1.13:1433;databaseName=test",
        "user" : "test",
        "password" : "test",
        "sql" : "select * from test",
        "index" : "test",
        "type" : "test",
        "elasticsearch.cluster" : "es",
        "elasticsearch.host" : "localhost",
        "elasticsearch.port" : 9300
   }
}
' | java \
    -cp "${lib}/*" \
       -Dlog4j.configurationFile=${bin}/log4j2.xml \
       org.xbib.tools.Runner \
       org.xbib.tools.JDBCImporter

**Comment by sandesh2014** [comment]
@jprante Could you let me know a way to get out of this

**Comment by jprante** [comment]
Please use 

```
{
  "type" : "jdbc",
  "jdbc" : {
    "url" : "jdbc:sqlserver://192.168.1.13:1433;databaseName=test",
    "user" : "test",
    "password" : "test",
    "sql" : "select * from test",
    "index" : "test",
    "type" : "test",
    "elasticsearch" : {
        "cluster" : "es",
        "host" : "localhost",
        "port" : 9300
    }
  }
}
```

**Comment by sandesh2014** [comment]
@jprante Thanks for your reply.

I have tried as suggested. But it is still throwing the same error. I'm using elasticsearch within the same instance. ES: 1.7 & JDBC Importer 1.6 & no shield is installed. Could you pl. let me know if there is something that i need to do.

Here is the log:

no cluster nodes available, check settings {cluster.name=es, host.0=localhost, port=9300, sniff=false, autodiscover=false, name=importer, client.transport.ignore_cluster_name=false, client.transport.ping_timeout=5s, client.transport.nodes_sampler_interval=5s}

**Comment by jprante** [comment]
I have too few information about how your cluster is running. You are sure that `es` is your cluster name?

**Comment by sandesh2014** [comment]
@jprante Thanks for trying to help me out.

Infact it is a single node cluster which has cluster name as "es" and running in the same machine (localhost) as JDBC Importer.

Can you let me know if there is something else i need to do or am i doing something wrong.

**Comment by jprante** [comment]
Maybe it's a version issue, let me check.

**Comment by sandesh2014** [comment]
@jprante could you let me know if elasticsearch-jdbc 1.6 is feasible with ES 1.7.0 version. If there are any compatible issues, shall revert it back to ES 1.6

**Comment by jprante** [comment]
I will release a new JDBC importer for ES 1.7.0 soon.

The current version 1.6.0.0 is not compatible to ES 1.7, the error is `org.elasticsearch.transport.RemoteTransportException: Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.info.NodesInfoResponse]`

**Comment by sandesh2014** [comment]
Thanks alot for you response. When can we expect JDBC Importer for ES 1.7.

Would you suggest to revert ES from 1.7 to 1.6 or would you suggest any workaround?

**Comment by jprante** [comment]
Please wait 30 minutes. JDBC import 1.7.0.0 build has started. You can then select ES 1.7.0. Note, the first three version digits of JDBC importer denote the compatible ES version.

**Comment by sandesh2014** [comment]
@jprante  thanks alot for your support. Really appreciate for your effort and help.

**Comment by jprante** [comment]
JDBC importer 1.7.0.0 is released. Thanks for the report.

**Comment by sandesh2014** [comment]
Thanks a ton @jprante . It works like a charm.

Really appreciate your support.. as always..

**Comment by MI1458** [comment]
Hello Team,

I am also getting below same error while import:
Error:org.elasticsearch.client.transport.NoNodeAvailableException: no cluster nodes available, check settings

ElasticSearch verion:6.0.0
jdbc version:elasticsearch-jdbc-2.3.4.1
SQL Server version :SQL2016 developer edition

I have installed it on my local machine.
I have tried most of the solutions from different forums. Please help me. Stuck on the issue since 1 week.
