### ISSUE TITLE
ElasticSearch-river: Problem in updating document partially or fully after changing data in DB

### ISSUE THREAD

**Issue by ashishgupta4486** [jprante/elasticsearch-jdbc#602]
@jprante 

I am new to ES and working on ES _river by calling stored procedure and getting documents successfully. Facing problem in updating existing document at ES after changing data in DB.

Tried schedule with _river, it gives me all the documents again and create new documents instead of updating existing ones for every call of cron expression. Tried with multiple combination based on search results but not able to find solution for the same.

Do I need to use _timestamp and let all the documents come with every time cron works and delete all old documents later using old _timestamp or there is another way to update document in ES.

Please share how can I fix this problem? Its little urgent.

Below is the _river I have created : 

PUT _river/INDEX_NAME/_meta
{
    "type":"jdbc",
    "jdbc": {
        "url":"jdbc:sqlserver://host:port;databaseName=DB_NAME",
        "user":"user",
        "password":"password",
        "sql":[{
            "statement": "STORED_PROCEDURE_NAME",
            "callable": true
            }],
        "index":"INDEX_NAME",
        "type":"TYPE_NAME",
        "schedule" : "0/30 * * * * ?"
    }
}

**Comment by jprante** [comment]
Use the `_id` pseudo column name in the SQL statement to address an Elasticsearch document.

**Comment by ashishgupta4486** [comment]
Thanks @jprante It is fixed. I used _id column and schedule and it worked.
