### ISSUE TITLE
Incorrect Uber Jar in ES Importer 1.7.0.1

### ISSUE THREAD

**Issue by sandesh2014** [jprante/elasticsearch-jdbc#606]
@jprante The latest release of ES importer (1.7.0.1) has the older uber jar (elasticsearch-jdbc-1.6.0.1-uberjar.jar) due to which it fails to run due to the version incompatibility. Infact, this should have elasticsearch-jdbc-1.7.0.0-uberjar.jar

**Comment by jprante** [comment]
Oh my. 

Thanks for reporting. I will push a new dist zip for 1.7.0.1

**Comment by jprante** [comment]
Pushed.

**Comment by sandesh2014** [comment]
@jprante No Problem.

Thanks for your efforts and prompt actions. Ofcourse, we have to support this..
