### ISSUE TITLE
problems with structured objects

### ISSUE THREAD

**Issue by davionxiang** [jprante/elasticsearch-jdbc#610]
![image](https://cloud.githubusercontent.com/assets/4226552/8928227/83345f32-354f-11e5-922d-ee24c3de5271.png)
![image](https://cloud.githubusercontent.com/assets/4226552/8928245/92e823b4-354f-11e5-97b4-e609cbafd9e7.png)
![image](https://cloud.githubusercontent.com/assets/4226552/8928251/a2060456-354f-11e5-92d4-7b805fd66c33.png)
![image](https://cloud.githubusercontent.com/assets/4226552/8928255/b06b65e0-354f-11e5-9143-0d78c062216e.png)

Hi, I encounter a problem when I try to construct structured objects. The results of my SQL are shown in the pictures above, I don't know why the two documents are different, one has two values in status and its _version is 1, but the other has only one value in status and its _version is 2.

Here is my SQL:
select "nova" as "_index", "apply" as "_type", applies.id as "_id", applies.user_id, applies.job_id, apply_tracking.apply_status as 'apply.status', apply_tracking.updated_at as 'apply.updated_at' from applies join apply_tracking on applies.id = apply_tracking.apply_id;

**Comment by wanghc85** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
