### ISSUE TITLE
Separate package with JDBC Importer binaries only (Apache license 2.0)

### ISSUE THREAD

**Issue by ArtyomBaranovskiy** [jprante/elasticsearch-jdbc#622]
Hi,

After renaming to Importer you started including thirdparty binaries into the JDBC Importer package, which have licenses different from Apache 2.0.
The company I'm working on has strict requirements for open-source software licenses, so could you please start building a separate "clean" package, free of viral licenses like GPL?

Thanks,
Artyom

**Comment by jprante** [comment]
After download and unpacking, you can delete the drivers you do not want to use.

**Comment by ArtyomBaranovskiy** [comment]
Thanks, the legal department confirmed that it's possible.
