### ISSUE TITLE
Import of Oracle XMLs in CLOB to elasticsearch as json documents

### ISSUE THREAD

**Issue by kubeusz88** [jprante/elasticsearch-jdbc#624]
Hello,

I'm facing following problem:

I have XMLs stored in Oracle DB in CLOB column, which I have to search using elasticsearch. I want to import it into elasticsearch. Right now I use elasticsearch-jdbc, but in elasticsearch document is stored as json with structure like above:

```javascript
      "_source":{"XML":"<?xml version=\"1.0\"?>\n\t<superset>\n\t\t<form>\n\t\t\t<field1>value1</field1>\n\t\t\t<field2>valu
e2</field2>\n\t\t\t<field3 name=\"button\"></field3>\n\t\t</form>\n\t</superset>"}
```

I would like to have a document stored in elasticsearch like a json file with a structure like above:
```javascript
      "_source":{  "form": {    "name": "Company Green",    "id": "1",    "field": [      {        "name": "name",        "r
equired": "false",        "type": "inputText",        "#text": "Alan"      }]}}
```

My question is:
__can elasticsearch-jdbc automatically import into elasticsearch as json document or is there a known method to achieve import from xml into json document in elasticsearch?__

Thanks in advance for any feedback.

**Comment by jprante** [comment]
There are many methods to create JSON from XML. It's a completely different format. JDBC importer does not provide XML support.

**Comment by kubeusz88** [comment]
Thank You for answer. I'm aware that there are many ways to create JSON from XML, but I hoped that JDBC importer can somehow support this way. Maybe it will in the nearest future :)

I close this issue.
