### ISSUE TITLE
Threading/resource issue when Elasticsearch is not accessable

### ISSUE THREAD

**Issue by feaster83** [jprante/elasticsearch-jdbc#648]
I have a problem on our Linux system with the feeders. Our server is running out of resources when only a single feeder instance is active. Note: We have a limited amount of File Descriptors.

I checked the count of file descriptors under /proc/\<pid>/fd/ with the command:
> ls /proc/\<pid>/fd | wc -l

and I see the the number of file descriptors is increasing. I think it will increased by 1 after each execution of the feeder. Most of the file descriptors are pipes between/in the same process. 

I debugged the code around the future/executors (Cron based), because pipes will be used between threads, but still can't find any issue in this part of the code. 

Note: we use a forked version of the elasticsearch-jdbc project and made some small changes (add some code to support a specific functionality). I think that the issue is in the original source and not related to our changes.

**Comment by jprante** [comment]
Thanks for the report.

I share your concern, there may be some resource leaks, because my code is not perfect. Of course I will investigate for myself, but also, I would be happy to see some reproducible code demos, so I could write unit tests to avoid such defects in future versions.

**Comment by feaster83** [comment]
I will continue the debugging of the code tomorrow. It should be solved before we can upgrade to the latest version. Maybe you have also any (other) idea what it possibly can cause?

If I can't find the cause then I will add more information about the usage/configuration.

**Comment by jprante** [comment]
Resource leaks can happen all over the place:

- the JDBC importer code, when threads go stale, or  when database connections do not close,
- the JDBC driver code, or
- Elasticsearch code, when the client is executed to transmit the data

A workaround would be to execute one-shot runs of the JDBC importer from the shell and exit the JVM process as sonn as possible. Repeated runs could be managed by cron, or other scheduling software.

**Comment by feaster83** [comment]
Issue closed. Environment issue/configuration with the Elasticsearch connection.

**Comment by feaster83** [comment]
There is still an issue with the Threading:

Reproduction:
- Start Feeder with interval of 10 seconds but without starting an Elasticsearch cluster 
- Connect with VisualVM (or a tool like that) to the Feeder. Each 10 seconds it creates ES clients but never cleaned then up.  
- Running threads is counting up.

**Comment by feaster83** [comment]
Issue solved. Pull request will be send today.
