### ISSUE TITLE
Use Suggest completion from SQL JDBC Request

### ISSUE THREAD

**Issue by jkeruzec** [jprante/elasticsearch-jdbc#650]
Hello,

I'm trying to use elasticsearch-jdbc with suggester options from Mapping in Elastic search.

I have configured a mapping with a completion type field and I create a SQL request like this :

Mapping :
```javascript
"tag_suggest": {
				   "type": "completion",
				   "index_analyzer": "simple",
				   "search_analyzer": "simple",
				   "payloads": false
				}
```
SQL :
```sql
select name as "tag_suggest.input" from my_table;
```
I thought that using the structured type "tag_suggest.input" will fill in the suggester but it does'nt.

Could someone explain me how to fill a suggester from SQL query ?

Thanks a lot,

**Comment by jprante** [comment]
You need to provide `tag_suggest.input` and `tag_suggest.output`, see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html

**Comment by jkeruzec** [comment]
Allright, It works !

Finally, I used in my test SQL request:
```sql
name as \"tag_suggest.input\", transaction_number as \"tag_suggest.output\", transaction_number as \"tag_suggest.payload.transactionId\"
````
The suggest response result is like this

```javascript
{
_shards: {
total: 5
successful: 5
failed: 0
}-
product_suggest: [1]
0:  {
text: "def"
offset: 0
length: 3
options: [5]
0:  {
text: "TST000000001"
score: 12
payload: {
transactionId: "TST000000001"
}-
}-
1:  {
text: "TST000000002"
score: 12
payload: {
transactionId: "TST000000002"
}-
}-
...
```

Thank you.
