### ISSUE TITLE
Index metrics to Elasticsearch

### ISSUE THREAD

**Issue by feaster83** [jprante/elasticsearch-jdbc#661]
[feature request]
If we index the Metrics to Elasticsearch it becomes possible to create an Elasticsearch plugin that displays the status of the feeders. I think it should be an optional feature that can be enabled by the JSON configuration of the feeder.

For example by the following configuration:
```json
"metrics" : {
            "enabled" : true,
            "interval" : "1m",
            "logger" : {
                "plain" : false,
                "json" : true,
                "elasticsearch" : true
            }
        }
```

**Comment by jprante** [comment]
Do you use log4j2?

It should be possible with some tweaks to index the logs into Elasticsearch itself with my appender https://github.com/jprante/log4j2-elasticsearch

**Comment by feaster83** [comment]
Nice!

That's what I want. Thanks!
