### ISSUE TITLE
Problem with type_mapping in mssql

### ISSUE THREAD

**Issue by yollandaarteinterior** [jprante/elasticsearch-jdbc#671]
Hi! I'm new from here!

I have a Issue when importing data into ES with MSSql.

It's my .bat program:
![image](https://cloud.githubusercontent.com/assets/9484121/10591995/9f278e40-768f-11e5-8329-421b0644b19f.png)

I need to change the default mapping in "remetente" field to be not analyzed.
When I run the .bat, everything is fine, but the field still analyzed.
![image](https://cloud.githubusercontent.com/assets/9484121/10591920/3ef180da-768f-11e5-81b8-4681fede72f5.png)

Any help will be apreciated!

Regards,

**Comment by yollandaarteinterior** [comment]
Hi, @jprante !

I try to use type_mapping with several ways, but not success with ES 1.7.2 and es-jdbc 1.7.2.1 with MSSql.
To contour my problem, I used dynamic_mapping, like this:
```javascript
curl -XPUT http://localhost:9200/sgd -d '{
   "mappings": {
      "protocolo": {
         "dynamic_templates": [
            {
               "campos_nao_analizados": {
                  "match": "*_na",
                  "match_mapping_type": "string",
                  "mapping": {
                     "type": "string",
                     "index": "not_analyzed"
                  }
               }
            },{
               "campos_fulltext": {
                  "match": "*",
                  "match_mapping_type": "string",
                  "mapping": {
                     "type": "string",
                     "analyzer": "brazilian"
                  }
               }
            }
         ]
      }
   }
}'
```

And rewrite the SQL to:
```sql
select p.IdenProt as _id, p.Reme as remente, p.Reme as rementente_na, p.NumrDocm as numero...
```

**Comment by jprante** [comment]
Please create indexes with settings and mapping before running JDBC importer, if `index_settings` or `type_mapping` does not work.

**Comment by yollandaarteinterior** [comment]
I tried, but after import data, the mapping was replaced.
