### ISSUE TITLE
Import db2 data usin JT400.jar Driver

### ISSUE THREAD

**Issue by arbh89** [jprante/elasticsearch-jdbc#673]
Is it possible to use the JT400 Driver to import data from a db2 database?

I have been trying using this configuration.

{
	"type": "jdbc",
	"jdbc": {
		"driver" : "com.ibm.as400.access.AS400JDBCDriver",
		"url": "jdbc:as400://MyAS400SERVER/database;",
		"user": "USERNAME",
		"password": "PASSWORD",
		"sql": "SELECT *  FROM MYTABLE",
		"index": "as400_schema",
		"type": "schema",
		"autocommit": "true"		
	}
}

I am getting the erros "No suitable driver found for jdbc:as400". i have already copied the jt400.jar to the lib folder.

Am i doing something wrong?

Thanks in advance.

**Comment by jprante** [comment]
Update your driver to a JDBC4 compliant version, e.g. this one https://github.com/piguangming/jt400

**Comment by arbh89** [comment]
Thanks, using the jdbc type 4 and removing the driver parameter solved the problem.
