### ISSUE TITLE
About jdbc river

### ISSUE THREAD

**Issue by RicherdLee** [jprante/elasticsearch-jdbc#685]
Hi Team 
 This is a question not a issue.
 I have used old version elasticsearch-jdbc as a river.
 Example:

curl -XPUT 'localhost:9200/_river/my_jdbc_river/_meta' -d '{
    "type" : "jdbc",
    "jdbc" : {
        "driver" : "com.mysql.jdbc.Driver",
        "url" : "jdbc:mysql://localhost:3306/test",
        "user" : "",
        "password" : "",
        "sql" : "select * from orders"
        "index" : "jdbc_index",
        "type" : "jdbc_type",
        "bulk_size" : 1000,
        "max_bulk_requests" : 50,
        "bulk_flush_interval" : "10s"
    }
}'
Now，elasicsearch-jdbc is not a plugin,I read https://github.com/jprante/elasticsearch-jdbc/wiki/JDBC-plugin-feeder-mode-as-an-alternative-to-the-deprecated-Elasticsearch-River-API 。
 Is't mean that i can only use shell to synchronous mysql data。
When i need to synchronous multiple mysql ，I need create multiple shell ？ Thank

**Comment by jprante** [comment]
Thanks for your request.

You have to run multiple JDBC importer on shell.

In a future version, I will find a better solution.

**Comment by RicherdLee** [comment]
Thanks for your replay
