### ISSUE TITLE
BaseTransportClient - [localhost/127.0.0.1:9300]

### ISSUE THREAD

**Issue by thebrunosantos** [jprante/elasticsearch-jdbc#689]
Hi!

I'm having a problem with "org.xbib.elasticsearch.support .client.BaseTransportClient" that insists in connect in localhost:9300, even if I pass the host in settings. 
I've changed the "network.host " in elasticsearch.yml to "localhost" and the JDBC worked! But in my network elasticsearch will dont. 

Here's my file: 

```
#!/bin/sh

bin=/usr/share/elasticsearch/elasticsearch-2.0.0/elasticsearch-jdbc-2.0.0.0/bin
lib=/usr/share/elasticsearch/elasticsearch-2.0.0/elasticsearch-jdbc-2.0.0.0/lib

echo '
{
    "elasticsearch" : {
         "cluster" : "elasticsearch",
         "host" : "srvidx",
         "port" : 9300
    },
    "type": "jdbc",
   "jdbc": {
      "driver": "com.microsoft.sqlserver.jdbc.SQLServerDriver",
      "url": "jdbc:sqlserver://SRVBD01;databaseName=DB",
      "user": "user",
      "password": "pass",
      "sql": " SELECT id as _id, * FROM table ",
      "poll": "10m",
      "strategy": "simple",
      "index": "transparencia",
      "type": "despesas"
   }
}
' | java \
    -cp "${lib}/*" \
    -Dlog4j.configurationFile=${bin}/log4j2.xml \
    org.xbib.tools.Runner \
    org.xbib.tools.JDBCImporter

```

And thats the line where the connection occurs: 
```
[15:56:03,870][INFO ][org.xbib.elasticsearch.support.client.BaseTransportClient][pool-3-thread-1] trying to connect to [localhost/127.0.0.1:9300]
```

_*UPDATE:*_
I'm using ElastichSearch 2.0 and JDBC 2.0.0.0.

Thanks!

**Comment by jprante** [comment]
You need to move everything under the `jdbc` element, like this

```
echo '
{
   "jdbc": {
      "url": "jdbc:sqlserver://SRVBD01;databaseName=DB",
      "user": "user",
      "password": "pass",
      "sql": " SELECT id as _id, * FROM table ",
      "index": "transparencia",
      "type": "despesas",
      "elasticsearch" : {
         "cluster" : "elasticsearch",
         "host" : "srvidx",
         "port" : 9300
      }
   }
}
' | java \
    -cp "${lib}/*" \
    -Dlog4j.configurationFile=${bin}/log4j2.xml \
    org.xbib.tools.Runner \
    org.xbib.tools.JDBCImporter
```

Note, that `poll, and `driver` is not supported any more, and there is also no more `strategy: simple`

**Comment by thebrunosantos** [comment]
Wow man!

It worked like a charm! 

I'm migrating to version 2.0, so it did not set the parameters yet.

Thank you so much.

**Comment by nikhil-sahu** [comment]
I am facing the same issue.
My Config is this:

{
    "type" : "jdbc",
    "jdbc" : {
        "schedule" : "0 0-59 0-23 ? * *",
        "statefile" : "statefile.json",
        "url" : "jdbc:mysql://localhost:3306/testseries",
        "user" : "***",
        "password" : "***",
        "sql" : "***",
        "index" : "tests",
        "type" : "tests",
        "autocommit":"true",
        "elasticsearch" : {
                "cluster" : "elasticsearch",
                "host":"localhost"
                "port" : 9200
        },
        "metrics" : {
            "enabled" : true
        }
    }
}


and I can see a log line as:
[17:43:00,813][INFO ][org.xbib.elasticsearch.helper.client.BaseTransportClient][pool-4-thread-1] trying to connect to [localhost/127.0.0.1:9200]

Not what I am expecting. ES is running on localhost:9200

**Comment by jprante** [comment]
Please open separate issue, do not add comments to old closed issues. 

JDBC importer 2.3.4.1 is for ES 2.3.4 only. 

Please use transport port 9300. HTTP on 9200 is not supported. ES 5 is also not supported yet.
