### ISSUE TITLE
parent/child doc can't create

### ISSUE THREAD

**Issue by mm-yuliang** [jprante/elasticsearch-jdbc#700]
I was trying to create parent/child doc from two tables. verified sql by checking returned records from command console. When I tried to use jdbc import to build docs in elasticsearch, the child docs won't create and the mapping(has parent) was not created also. 

UPDATE: found the issue, the mapping was not created correctly before I run jdbc import to pull data in. 
followed the example at:
https://www.elastic.co/guide/en/elasticsearch/guide/current/parent-child-mapping.html

PUT /company
{
  "mappings": {
    "branch": {},
    "employee": {
      "_parent": {
        "type": "branch" 
      }
    }
  }
}

**Comment by jprante** [comment]
I can not see in the SQL statement or in the mapping that there is parent/child.

**Comment by mm-yuliang** [comment]
Hi Jorg, thanks for the prompt response!


in child doc:

"SELECT m.id as _id, *m.wiffiti_entry_id* as *_parent*, m.context_ref_id as
\"appconfigId\..."

in parent doc:
"sql" : "SELECT *we.id <http://we.id>* as _id, we.id as \"id\",
we.account_avatar_id as \"accountAvatarId\", ...... FROM ...... WHERE
...... "

child doc uses a different type from parent doc.
m.wiffiti_entry_id in child doc = we.id in parent doc, both are int data
type in MySQL DB.

what else needed? type mapping?




On Thu, Nov 19, 2015 at 1:12 PM, Jörg Prante <notifications@github.com>
wrote:

> I can not see in the SQL statement or in the mapping that there is
> parent/child.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jprante/elasticsearch-jdbc/issues/700#issuecomment-158141260>
> .
>



-- 

OBIE WINNER 2010-2014

*YULIANG CHEN*
SOFTWARE ENGINEER

T 407 478 8163  F 407 478 8174  C 225 931 1890
<+yuliang.chen@monstermedia.net>
STAY CONNECTED WITH US FOR
THE LATEST OOH INNOVATIONS
<http://facebook.com/MonsterMediaOOH> |  <http://twitter.com/_MonsterMedia>

WWW.MONSTERMEDIA.NET <http://www.monstermedia.net/>
555 SOUTH LAKE DESTINY DRIVE
ORLANDO, FLORIDA, 32810

**Comment by mm-yuliang** [comment]
@jprante can you have a look of this? thanks!
