### ISSUE TITLE
csv importer error: driver does not support setQueryTimeout(), skipped

### ISSUE THREAD

**Issue by jbwl** [jprante/elasticsearch-jdbc#701]
Hi, I am running into this error when trying to import a CSV file. Both your and the "official" CSV driver give the same error.

    [importer.jdbc.source.standard][pool-2-thread-1] driver does not support setQueryTimeout(), skipped

The import never starts as the script exits at this point.
I am using these versions on Ubuntu 14.04:

elasticsearch 1.7.2
elasticsearch-jdbc-1.7.2.1-uberjar.jar
jbdc-driver-csv-1.0.0.jar

Please let me know if you need more information.

**Comment by jprante** [comment]
The message is just a warning and is harmless.

What is the import specification?

**Comment by jbwl** [comment]
Hello Jörg, this is the importer specification. The file is tab-separated.
I am using your JDBC importer with the MySQL driver on this cluster without a problem, when I try to use the CSV driver, the import doesn't start. 
I think the biggest problem is I don't get any log or error messages to be able to debug this on my  own.

```json
type: "jdbc",
    jdbc: {
        driver: "org.xbib.jdbc.csv.CsvDriver",
        url: "jdbc:xbib:csv:/path/to/my/file?separator=TAB",
        user: "",
        password: "",
        index: "salesdata",
        type: "sale",
        sql: "SELECT * FROM 'salesdata.tsv'",
        elasticsearch: {
            cluster: "mycluster",
            host: "127.0.0.1",
            port: 9300
        },
        metrics: {
            enabled: true,
            interval: "1m",
            logger: {
                plain: false,
                json: true
            }
        }
    }
```

**Comment by jbwl** [comment]
I found the problem. The driver is adding a ".csv" extension to the filename given in the query, so the file is not found as the suffix is .tsv

I would propose to include this in the documentation in the csv section.

**Comment by jprante** [comment]
It is documented at https://github.com/jprante/jdbc-driver-csv but I agree it can help to add a note at JDBC importer doc as well.
