### ISSUE TITLE
Does elasticsearch-jdbc can handle notify events ?

### ISSUE THREAD

**Issue by mickaelperrin** [jprante/elasticsearch-jdbc#705]
Hi,

I aim to use elasticsearch-jdbc to do real-time synchronisation of a PostgreSQL database with an ES cluster.

I wrote a little python script that listen to PostgreSQL for notify events. When an event is thrown, I launch ES-jdbc with a specific query in the JSON config, mainly with the ID of the ROW to be indexed/updated in ES.

However, this works only for the first item as the SQL query is not updated while ES-jdbc is running.

I was wondering if there was some ways to use ES-jdbc this way (using notify events effectively). Mainly, what I would like to achieve is : 
- Establish a persistent connection with DB to avoid connect/reconnect for each query.
- Give a specific query to run on the DB to fetch Data for each notify event.

Thanks for your advices,

**Comment by mickaelperrin** [comment]
Forgot my question, I think this is absolutely not the way to use elasticsearch-jdbc. 

I finally handle the sync with ES directly in the python script that listen for PGSQL events.

I will use elasticsearch-jdbc to perfom initial indexations.

Thanks,

**Comment by jprante** [comment]
I'd be glad if notification events would be part of JDBC. But it isn't.

**Comment by mickaelperrin** [comment]
FYI If I am not wrong, this alternate Postgres JDBC driver handles some advanced features and asynchronous notifications: https://github.com/impossibl/pgjdbc-ng/

But, of course, this is only for PGSQL.
