### ISSUE TITLE
What is the SQL syntax to create a nested structure?

### ISSUE THREAD

**Issue by iyerdude** [jprante/elasticsearch-jdbc#721]
I am looking to create a nested structure in Elasticsearch using elasticsearch-jdbc, say Employee Details nested under Branch. Branch details nested under Country.
I am clueless on how to define my SQL in the .sh file. 
I tried inner joins, this added value only in the parent - Country and not in the nested types. 
Adding "as country.branch.name" after a column name also doesn't work.

@jprante Can you please help me with this immediately. I am working on a tight deadline.

**Comment by iyerdude** [comment]
Found the solution.

**Comment by ale0xB** [comment]
Hello, can you explain what your solution was? facing the same problem here
