### ISSUE TITLE
timezone does not effect

### ISSUE THREAD

**Issue by tantou** [jprante/elasticsearch-jdbc#731]
```json
{
  "_index": "ia-log",
  "_type": "log-access",
  "_id": "2950",
  "_score": null,
  "_source": {
    "auth": "",
    "backend_serv_time": 15,
    "backend_server": "10.32.68.252:8080",
    "backendfailover": "",
    "brws": "",
    "brws_v": "",
    "conn_times": 5795286104,
    "cookie_oc": "",
    "cookie_w_uuid": "",
    "ctime": "2015-12-20",
    "domain": "pms.dingdanggj.com",
    "dt": "20151220",
    "hour": "23",
    "httptype": "",
    "identd": "",
    "ip": "114.248.230.30",
    "method": "POST",
    "os": "",
    "os_v": "",
    "protocol": "HTTP/1.1",
    "referer": "",
    "rsp_len": 1255,
    "serv_time": 18,
    "slug": "",
    "srvname": "yf-nginx-web01.yf.sankuai.com",
    "status": "200",
    "time": "2015-12-20 23:59:53",
    "ua": "com.meituan.pms.ep/97 (unknown, iPhone OS 8.0.2, iPhone, Scale/2.000000)",
    "ufe": "",
    "url": "/api/v1/pms/api/order/query?bid=750fd42bf5f73c33ded839b8322a3236"
  },
  "fields": {
    "time": [
      1450655993000
    ],
    "ctime": [
      1450569600000
    ]
  },
  "sort": [
    1450655993000
  ]
}
```
the field `time` in _source is : `"2015-12-20 23:59:53"` ,but the time in `fields` is :`1450655993000`
and I set the 'timezone':'CTT' (Asia/Shanghai)  has no any effect
the time in fields  has faster than the time in `_source `   `8 hours`
Could you please help me to figure out why?

**Comment by jprante** [comment]
Can you give the SQL statement?

You should check how to convert SQL timestamp at DB side to UTC.

**Comment by tantou** [comment]
```
select id as _id,time,auth,backend_serv_time,backend_server,backendfailover,brws,brws_v,conn_times,cookie_oc,cookie_w_uuid,ctime,domain,dt,hour,httptype,identd,ip,method,os,os_v,protocol,referer,rsp_len,serv_time,slug,srvname,status,ua,ufe,url  from ia_log_accesslog
```

**Comment by tantou** [comment]
conver SQL timestamp at DB side to `UTC` can resolve the problem ?

**Comment by jprante** [comment]
Yes. `timezone` parameter is only for the case when JDBC timestamps have non-UTC timezone. UTC is Elasticsearch default timezone.

**Comment by tantou** [comment]
could you tell me how to set the timestamp to UTC ?

**Comment by jprante** [comment]
It depends on your DB.

**Comment by tantou** [comment]
my DB is mysql

**Comment by tantou** [comment]
I want to concat `+0800` to the time field , I the string does not effect,and I also don't know the correct syntax
```
"sql" : "select concat(time,'+0800')as time,createTime,name, id as _id from accesslog",
```

**Comment by jprante** [comment]
Use something like

```
SELECT 
CONVERT_TZ(`timestamp_field`, @@session.time_zone, '+00:00') AS `utc_datetime` 
FROM `table_name`
```

**Comment by tantou** [comment]
```
"select concat(time,'+0800')as time,createTime,name, id as _id from accesslog"
```
the `+` has disapear in the result,how to make it visible
like:`2015-12-22 12:44:33+0800`
in the sql string?

**Comment by jprante** [comment]
This is not a string, it's a timestamp with a timezone. You can not `concat`.

**Comment by tantou** [comment]
my field `time` is a string,not a timestamp,so I want to concat ,but the `+` has disapear

**Comment by jprante** [comment]
I do not understand. Your question was about timezone. There is no timezone in a string.

**Comment by tantou** [comment]
my field time is a string, I had test if concat with `+0800` , it can be format correct, but I can not get the correct string :`2015-12-22 12:44:33+0800`,just get the `2015-12-22 12:44:33800`

**Comment by tantou** [comment]
to resolve the problem, I got two solution:
1. modify the timestamp to UTC
2. concat the `+0800`

**Comment by tantou** [comment]
Can you tell me how to concat the `+0800` in the sql string:
```
"select concat(time,'+0800')as time,createTime,name, id as _id from accesslog"
```
This is my second solution
Thanks in advanced !

**Comment by jprante** [comment]
You can not concat a timezone.

**Comment by tantou** [comment]
I just want to concat a string field ,not a timezone ,and  I have got the solution to concat:
```
"select concat(time,'0x2b','0','0800')as time,createTime,name, id as _id from accesslog"
```
then I can got the correct string :`2015-12-22 12:22:33+0800` 
just transform `x` to the hex `0x2b`
Thank you ! I have got the solution to resolve my problem !
