### ISSUE TITLE
no cluster nodes available, check settings 

### ISSUE THREAD

**Issue by amlun** [jprante/elasticsearch-jdbc#736]
>no cluster nodes available, check settings {cluster.name=elasticsearch, max_actions_per_request=1000, m ax_concurrent_requests=4}

When I upgrade the elasticsearch-jdbc to version 2.1.1.0,I got this error.When I use verion 2.1.0,it is ok~

**Comment by amlun** [comment]
My elasticsearch config is `cluster.name: blog-search`
My elasticsearch-jdbc is `"elasticsearch":{"cluster": "blog-search"}`

**Comment by jprante** [comment]
Thanks. I made a small mistake in 2.1.1.0

Please wait for 2.1.1.1 or you can try

```
 "elasticsearch": {
  "cluster": {
    "name": {
      "blog-search"
   }
   ...
  }
}
```

**Comment by amlun** [comment]
@jprante 
OK~
