### ISSUE TITLE
Issues with setting elasticsearch.host after 2.1.1.x

### ISSUE THREAD

**Issue by andersha** [jprante/elasticsearch-jdbc#738]
I've upgraded to elastic 2.1.1 and jdbc 2.1.1.1. I had to change my config from 

"elasticsearch.cluster": "'${ELASTIC_CLUSTER}'",

to 

"cluster.name": "'${ELASTIC_CLUSTER}'",

to make it use the correct cluster.

But I am not able to set the elasticsearch.host. Regardless of what I insert into the "jdbc" JSON I cannot get it to pick it up, it just uses localhost.

**Comment by jprante** [comment]
Doh. I think I made a mess, please wait for after christmas to let me clean it up. Thanks.

**Comment by jprante** [comment]
Just released 2.1.1.2 with fix for client connection configuration. Sorry for the noise.

**Comment by andersha** [comment]
Brilliant. Will test out the changes.

**Comment by andersha** [comment]
Tested. Works well for me now without editing configuration. Good work!
