### ISSUE TITLE
Release 2.2.0 seems to contain 2.1.1.2

### ISSUE THREAD

**Issue by eddiejaoude** [jprante/elasticsearch-jdbc#774]
`elasticsearch-jdbc` **release** `2.2.0` seems to contain `2.1.1.2` not `2.2.*`? 

Where as **master** seems to contain the `2.2.*` version for **Elasticsearch** `2.2`.

I would prefer to use a **release** rather than **master**.

When will a `2.2.*` **release** be created for `elasticsearch-jdbc`?

**Comment by jezgomez** [comment]
:+1:  I have exactly the same issue.

**Comment by jumblesale** [comment]
yeah I am having this problem too

**Comment by jprante** [comment]
Thanks for the notice, yes, I have been aware of messing things up. Sorry!

I pushed some more commits and released a fix version 2.2.0.1, nothing fancy added, only a new build. I'm trying to move to a pure gradle build.

Quick download link:

http://xbib.org/repository/org/xbib/elasticsearch/importer/elasticsearch-jdbc/2.2.0.1/elasticsearch-jdbc-2.2.0.1-dist.zip

**Comment by eddiejaoude** [comment]
Ok thanks, will take a look

**Comment by eddiejaoude** [comment]
Thanks. Looks good! :+1:
