### ISSUE TITLE
elasticsearch-jdbc to mssqlserver

### ISSUE THREAD

**Issue by caozhiyuan** [jprante/elasticsearch-jdbc#787]
hi , i got a problem 
![qq 20160323091048](https://cloud.githubusercontent.com/assets/3415285/13972841/5329aa10-f0d7-11e5-8d19-8e324f181303.png)
![qq 20160323091243](https://cloud.githubusercontent.com/assets/3415285/13972845/65b0e310-f0d7-11e5-86bf-656a89183a39.png)

can't Import mssqlserver data to elasticsearch

@echo off

set LIB="D:\elasticsearch-jdbc-2.2.0.0-dist\elasticsearch-jdbc-2.2.0.0\lib\*"
set BIN="D:\elasticsearch-jdbc-2.2.0.0-dist\elasticsearch-jdbc-2.2.0.0\bin"

REM ???
echo {^
    "type" : "jdbc",^
    "jdbc" : {^
        "url" : "jdbc:sqlserver://192.168.100.10,6666;databaseName=ShiHang0624",^
        "user" : "sa",^
        "password" : "",^
        "sql" :  "select *,id as _id from Product",^
        "index" : "metaproduct",^
        "type" : "product"^
      }^
}

"%JAVA_HOME%\bin\java" -cp "%LIB%" -Dlog4j.configurationFile="%BIN%\log4j2.xml" "org.xbib.tools.Runner" "org.xbib.tools.JDBCImporter"

pause

**Comment by jprante** [comment]
Sorry, I don't know Windows.
