### ISSUE TITLE
elasticsearch-jdbc-2.3.1.0 No lib folder? 

### ISSUE THREAD

**Issue by JohnTian** [jprante/elasticsearch-jdbc#804]
elasticsearch-jdbc-2.3.1.0.tar.gz don't have **lib** folder!
Why?
so how can I import **MySql** data use my.sh which will use **lib** folder in **linux** OS.

anyone could help me out ?
thanks very much.

**Comment by jprante** [comment]
There is no tar.gz

Can you please use `elasticsearch-jdbc-2.3.1.0-dist.zip` in folder `http://xbib.org/repository/org/xbib/elasticsearch/importer/elasticsearch-jdbc/2.3.1.0/` ?

**Comment by JohnTian** [comment]
thanks @jprante . I found the **lib** folder. But when I use run **sh my.sh**. I got the following error:
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/xbib/tools/Runner : Unsupported major.minor version 52.0
could you help me out, please?

**Comment by JohnTian** [comment]
@jprante Thanks a lot.

**Comment by jprante** [comment]
Accidentally, this release is compiled only for Java 8 Runtime. Please use JDK 8.

**Comment by JohnTian** [comment]
@jprante yeah, I found it. Thanks for your help.
