### ISSUE TITLE
Help! Is there a build for 1.7.5?

### ISSUE THREAD

**Issue by iommi1** [jprante/elasticsearch-jdbc#806]
I need to upgrade but my feeders need help
thanks!

**Comment by jprante** [comment]
Doesn't JDBC importer 1.7.3.0 work?

http://xbib.org/repository/org/xbib/elasticsearch/importer/elasticsearch-jdbc/1.7.3.0/

**Comment by iommi1** [comment]
Yes thanks a lot!
