### ISSUE TITLE
Could not find or load main class org.xbib.tools.Runner

### ISSUE THREAD

**Issue by eplelis** [jprante/elasticsearch-jdbc#808]
I am stuck with this error trying to use JDBCImporter into elasticsearch ver 2.3.1.  I unpacked elasticsearch-jdbc-2.3.1.0-dist.zip as described and copied ojdbc7.jar into the lib directory.  I modified oracle-connection-properties.sh to suit my setup.

$ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

Contents of my lib directory - /cygdrive/c/ElasticSearch/elasticsearch-jdbc-2.3.1.0/lib
commons-cli-1.3.1.jar
compress-lzf-1.0.2.jar
derby-10.12.1.1.jar
elasticsearch-2.3.1.jar
elasticsearch-helper-2.3.1.0.jar
elasticsearch-jdbc-2.3.1.0.jar
guava-18.0.jar
h2-1.4.191.jar
HdrHistogram-2.1.6.jar
hppc-0.7.1.jar
hsqldb-2.3.3.jar
jackson-core-2.6.2.jar
jackson-dataformat-cbor-2.6.2.jar
jackson-dataformat-smile-2.6.2.jar
jackson-dataformat-yaml-2.6.2.jar
jdbc-driver-csv-1.0.0.jar
joda-convert-1.2.jar
joda-time-2.8.2.jar
jsr166e-1.1.0.jar
jts-1.13.jar
log4j-api-2.5.jar
log4j-core-2.5.jar
log4j-slf4j-impl-2.5.jar
lucene-analyzers-common-5.5.0.jar
lucene-backward-codecs-5.5.0.jar
lucene-core-5.5.0.jar
lucene-grouping-5.5.0.jar
lucene-highlighter-5.5.0.jar
lucene-join-5.5.0.jar
lucene-memory-5.5.0.jar
lucene-misc-5.5.0.jar
lucene-queries-5.5.0.jar
lucene-queryparser-5.5.0.jar
lucene-sandbox-5.5.0.jar
lucene-spatial3d-5.5.0.jar
lucene-spatial-5.5.0.jar
lucene-suggest-5.5.0.jar
mysql-connector-java-5.1.38.jar
netty-3.10.5.Final.jar
ojdbc7.jar
postgresql-9.4.1208.jre7.jar
securesm-1.0.jar
slf4j-api-1.7.12.jar
snakeyaml-1.15.jar
spatial4j-0.5.jar
t-digest-3.0.jar

My job -
#!/bin/sh

# This example is a template to connect to Oracle
# The JDBC URL and SQL must be replaced by working ones.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
bin=${DIR}/../bin
lib=${DIR}/../lib

echo '
{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:oracle:thin:@xx.xx.xx.xx:1521/SID",
        "connection_properties" : {
            "oracle.jdbc.TcpNoDelay" : false,
            "useFetchSizeWithLongColumn" : false,
            "oracle.net.CONNECT_TIMEOUT" : 10000,
            "oracle.jdbc.ReadTimeout" : 50000
        },
        "user" : "user",
        "password" : "pwd",
        "sql" : "select user_id as _id,user_id,pc_email_address,first_name,last_name,phone1,phone2 from users_tbl1"
        "index" : "myoracle",
        "type" : "myoracle",
        "elasticsearch" : {
            "cluster" : "elasticsearch",
            "host" : "localhost",
            "port" : 9300
        },
        "max_bulk_actions" : 20000,
        "max_concurrent_bulk_requests" : 10,
        "index_settings" : {
            "index" : {
                "number_of_shards" : 1,
                "number_of_replica" : 0
            }
        }
    }
}
' | java \
    -cp "${lib}/*" \
    -Dlog4j.configurationFile=${bin}/log4j2.xml \
     org.xbib.tools.Runner \
     org.xbib.tools.JDBCImporter

Error: Could not find or load main class org.xbib.tools.Runner

Hope that you can tell me what I am doing wrong.

Thanks,
Eric

**Comment by jprante** [comment]
Please replace 

```
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
```

with

```
DIR= /cygdrive/c/ElasticSearch/elasticsearch-jdbc-2.3.1.0/
```

DIR is the shell variable for the JDBC importer directory.

**Comment by eplelis** [comment]
Changed the script as advised, but no luck!  Is this some form of version compatibility issue?

$ sh -x jdbc_import.sh
+ DIR=/cygdrive/c/ElasticSearch/elasticsearch-jdbc-2.3.1.0
+ bin=/cygdrive/c/ElasticSearch/elasticsearch-jdbc-2.3.1.0/bin
+ lib=/cygdrive/c/ElasticSearch/elasticsearch-jdbc-2.3.1.0/lib
+ echo '
{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:oracle:thin:@xx.xx.xx.xx:1521/SID",
        "connection_properties" : {
            "oracle.jdbc.TcpNoDelay" : false,
            "useFetchSizeWithLongColumn" : false,
            "oracle.net.CONNECT_TIMEOUT" : 10000,
            "oracle.jdbc.ReadTimeout" : 50000
        },
        "user" : "user",
        "password" : "pwd",
        "sql" : "select user_id as _id,user_id,pc_email_address,first_name,last_name,phone1,phone2 from users_tbl1"
        "index" : "myoracle",
        "type" : "myoracle",
        "elasticsearch" : {
            "cluster" : "elasticsearch",
            "host" : "127.0.0.1",
            "port" : 9300
        },
        "max_bulk_actions" : 20000,
        "max_concurrent_bulk_requests" : 10,
        "index_settings" : {
            "index" : {
                "number_of_shards" : 1,
                "number_of_replica" : 0
            }
        }
    }
}
'
+ java -cp '/cygdrive/c/ElasticSearch/elasticsearch-jdbc-2.3.1.0/lib/*' -Dlog4j.configurationFile=/cygdrive/c/ElasticSearch/elasticsearch-jdbc-2.3.1.0/bin/log4j2.xml org.xbib.tools.Runner org.xbib.tools.JDBCImporter
Error: Could not find or load main class org.xbib.tools.Runner

**Comment by jprante** [comment]
No, it's not a version incompatibility. The java command has no class path.

`elasticsearch-jdbc-2.3.1.0.jar` contains `org.xbib.tools.Runner` so you should double check why the class path is not containing the class.

**Comment by eplelis** [comment]
The size of the elasticsearch-jdbc-2.3.1.0.jar file seems small.  I also downloaded elasticsearch-jdbc-2.3.1.0-all.jar, which is so much larger, renamed it to elasticsearch-jdbc-2.3.1.0.jar but to no avail.

-rwxrwx---+ 1 elelis Domain Users 25279425 Apr 15 15:57 /cygdrive/c/ElasticSearch/elasticsearch-jdbc-2.3.1.0/lib/elasticsearch-jdbc-2.3.1.0-all.jar
-rwxrwx---+ 1 elelis Domain Users   129225 Apr 15 16:30 /cygdrive/c/ElasticSearch/elasticsearch-jdbc-2.3.1.0/lib/elasticsearch-jdbc-2.3.1.0.jar

**Comment by jprante** [comment]
Do not use the 'all' artifact.

Please check if `java` execution with `-cp` is correct.
```
jar tvf elasticsearch-jdbc-2.3.1.0.jar | grep Runner
  1214 Sat Apr 09 16:12:00 CEST 2016 org/xbib/tools/Runner.class
```

**Comment by eplelis** [comment]
I got the same result -
$ jar tvf elasticsearch-jdbc-2.3.1.0.jar | grep Runner
  1214 Sat Apr 09 16:12:00 EDT 2016 org/xbib/tools/Runner.class

$ jar tvf elasticsearch-jdbc-2.3.1.0.jar | grep Importer
  1142 Sat Apr 09 16:12:00 EDT 2016 org/xbib/tools/JDBCImporter$1.class
   785 Sat Apr 09 16:12:00 EDT 2016 org/xbib/tools/JDBCImporter$2.class
 14488 Sat Apr 09 16:12:00 EDT 2016 org/xbib/tools/JDBCImporter.class

I am not a java programmer, so I apologize if my question does not make any sense.  Does it matter if class name in the jar file org/xbib/tools/Runner.class different from the script org.xbib.tools.Runner?

java -cp '/cygdrive/c/ElasticSearch/elasticsearch-jdbc-2.3.1.0/lib/*' -Dlog4j.configurationFile=/cygdrive/c/ElasticSearch/elasticsearch-jdbc-2.3.1.0/bin/log4j2.xml org.xbib.tools.Runner org.xbib.tools.JDBCImporter 

Error: Could not find or load main class org.xbib.tools.Runner

**Comment by jprante** [comment]
Is this Windows (Cygwin)? Maybe the asterisk '*' in `-cp` does not work?

**Comment by eplelis** [comment]
Yes, I am running it on windows 7.  Cygwin lets you run linux commands on windows.

**Comment by jprante** [comment]
Again, double check why the class path in java `-cp` argument does not contain the jars. This is the job of cygwin.

**Comment by eplelis** [comment]
Thank you very much for your helpful insights!

I was able to get passed this issue by changing my script to -
java \
    -cp "C:\\ElasticSearch\\elasticsearch-jdbc-2.3.1.0\\lib\\*" \
    -Dlog4j.configurationFile=C:\\ElasticSearch\\elasticsearch-jdbc-2.3.1.0\\bin\\log4j2.xml \
     org.xbib.tools.Runner \
     org.xbib.tools.JDBCImporter

Apparently, java on cygwin uses windows path nomenclature.

**Comment by dileepnarne** [comment]
Hai 
i new to java  ,Pl Help  me to close this error , 

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/xbib/tools/Runner : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by jprante** [comment]
@dileepnarne Please open a new issue and do not append to old ones, because it has nothing to do with it.

You should use Java 8 for JDBC importer.

**Comment by matt212** [comment]
Hi @jprante , 

if you refer below gist 
[postgresql-simple-example](https://gist.github.com/matt212/57e9d17b7afb98baadfca738d3173bd7)

the error still persist " Could not find or load main class org.xbib.tools.Runner"" ,
Any pointers on how to resolved it !
