### ISSUE TITLE
Mapper exception: cannot be changed from type [boolean] to [long]

### ISSUE THREAD

**Issue by AbsoluteResults** [jprante/elasticsearch-jdbc#810]
I am using ES 2.2.0 and elasticsearch-jdbc-2.2.0.0 reading from a MySQL database. I had a script running on ES 1.6 previously which worked perfectly, and tried running it on the new version and got the following error on every row from the database:

message [java.lang.IllegalArgumentException: mapper [trainerMadeAppointment] cannot be changed from type [boolean] to [long]

The mapping for his field is very simple and has not changed from 1.7:

"trainerMadeAppointment": {
     "type": "boolean"
 }

Coming out of the database the issue can be one of many values so the SQL statement I am using has multiple CASE statements that all either set trainerMadeAppointment to TRUE or FALSE. No matter what I try to return as a value I get this exception for this field. I tried returning TRUE, true, and 1 and always the same error. I even tried removing all casts and simply set "TRUE as trainerMadeAppointment" and that also failed. I read through https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#migration-bool-fields and https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-2.0.html so I know the "T"/"F" vs true/false now.

I also tried setting the return value as "true" and that errored, as expected, with: 

message [java.lang.IllegalArgumentException: mapper [trainerMadeAppointment] cannot be changed from type [boolean] to [string]

I even tried changing the mapping in Elasticsearch to long instead of boolean and STILL got this error

If I manually send in a cURL request it works as I would expect and the value is a boolean

curl -X PUT -H "Content-Type: application/json" -d '{
>   "trainerMadeAppointment":true
> }' "http://es-stage:9220/test/f/3"

So rather than an ES mapping problem it looks like it is having issues with the values being returned from the SQL query. Has anyone else seen this issue in 2.x and/or have any recommendations for what else to look for or try? I can CAST I suppose if I need to but that must have changed in the codebase since I downloaded the 1.7 version months ago.

Thanks in advance

**Comment by jprante** [comment]
Type `boolean` has gone from Elasticsearch 2 and was replace by `long`.
What is the column type for `trainerMadeAppointment`, is it `BOOLEAN` ?
If you can give the SQL statement, it would be possible to reproduce.

**Comment by AbsoluteResults** [comment]
This was totally my fault not watching the "type" parameter in the mappings :)

BTW boolean still works just fine. I did read they were moving away from the T and F but sending from your awesome program using the TRUE and FALSE MySQL keywords to a BOOLEAN mapped field is completely fine. Sorry about that.
