### ISSUE TITLE
java.io.StreamCorruptedException: invalid internal transport message format, got (48,54,54,50)

### ISSUE THREAD

**Issue by amalrik** [jprante/elasticsearch-jdbc#812]
Hi
I'm getting this error when I try to start elasticsearch-jdbc with this shell script.
(sensite information are obfuscated with *)
```bash
bin=./bin
lib=./lib

echo '{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:mysql://*:3306/*",
        "user" : "*",
        "password" : "*",
        "sql" : "select * from addresses",
        "index": "bonus_addresses",
        "elasticsearch" : {
             "cluster" : "*",
             "host" : "*",
             "port" : 80 
        }
    }
}' | java \
       -cp "${lib}/*" \
       -Dlog4j.configurationFile=${bin}/log4j2.xml \
       org.xbib.tools.Runner \
       org.xbib.tools.JDBCImporter
```

the full log is in [this gist](https://gist.github.com/amalrik/cf7b6f4d29387c49590d8db13186940a)

Here is the stack i'm using:

- Ubuntu 14.04 LTS
- java "1.8.0_92"
- elasticsearch  1.5.2 -> i'm using amazon elasticsearch service
- elasticsearch-jdbc 1.5.2.0

I have no idea why this is happening, so any help would be appreciated.

**Comment by jprante** [comment]
You can not use port 80 (HTTP) with JDBC importer.

HTTP client is work in progress.

**Comment by amalrik** [comment]
Thanks @jprante
