### ISSUE TITLE
dispatch to several index within one import batch

### ISSUE THREAD

**Issue by iamtiancaif** [jprante/elasticsearch-jdbc#813]
will elasticsearch-jdbc support the feature that customizing output like logstash?
here is an example.
doc1: {"id":1, "type":"a", "message": "blabla"}
doc2: {"id":2, "type":"b", "message": "blabla"}

if (type == a) {
    //  index into index hot
}
else if (type == b) {
    // index into index cold.
}。

and similar operation uopn type.

**Comment by jprante** [comment]
You can send
```
doc1: {"_id":1, "_index":"a", "message": "blabla"}
doc2: {"_id":2, "_index":"b", "message": "blabla"}
```
to index into `a` or `b`

**Comment by iamtiancaif** [comment]
Does it mean the value of _index will override that one inside configuration files？
Is this a feature of your project or of es index api? I just scaned over es reference and didn't find it.

Thanks～

**Comment by jprante** [comment]
With SQL pseudo columns of `_index`, `_type`, and `_id` in JDBC importer SQL statement, you can address where the ES document should be indexed.

They are translated to index/type/id in the ES indexing API.
