### ISSUE TITLE
issues with text starting with [.*] when detect_json true 

### ISSUE THREAD

**Issue by tulay** [jprante/elasticsearch-jdbc#814]
From postgres(9.4.6) to elasticsearch(2.3.1) using elasticsearch-jdbc-2.3.1.0, I am indexing records that have text and json fields. detect_json is enabled. Unfortunately,  titles that start with a pattern [.*] are indexed as an array. ES mapping still shows the field as  string type. I am not sure how this is happening. 

One such example title is _[7](3,5)TROPONOPHANES AND [9](3,5)TROPONOPHANES AND THE CORRESPONDING HYDROXYTROPYLIOPHANES_ This shows up as "title" : [ 7 ] in the ES _source field unless you add a quotation or replace the first character somehow. 
Any idea how to debug or work around this?

**Comment by tulay** [comment]
My guess is this is coming from the logic in PlainKeyValueStreamListener.java
with scala repl:
```
import org.elasticsearch.common.xcontent.json.JsonXContent
val s="[7](3,5)TROPONOPHANES AND [9](3,5)TROPONOPHANES AND THE CORRESPONDING HYDROXYTROPYLIOPHANES"
val parser = JsonXContent.jsonXContent.createParser(s);
val token=parser.nextToken()
parser.list()
java.util.List[Object] = [7]
```

I don't want to do any special formatting in general but as a quick fix I added an extra character at the beginning of the titles that could potentially parsed as array or map (which is the case if the text starts with something like {8:9}).

**Comment by jprante** [comment]
Strings with `[` or `{` and correspondent closing braces `]` or `}` pass the JSON parser and are indexed as JSON when `detect_json` is enabled. If you don't want this, you must disable `detect_json`

**Comment by tulay** [comment]
I understand that but won't you agree that the text in my example is not a valid json to begin with? There is a loss of information. I'd expect it to default to indexing the value as text.

**Comment by jprante** [comment]
`[7]` is a valid JSON list. I agree that this data is non-sense in JSON. But JSON parser can not make an opinion about that, sorry.
