### ISSUE TITLE
 xbib.org down

### ISSUE THREAD

**Issue by rahul-coatue** [jprante/elasticsearch-jdbc#818]
Looks like xbib.org repo is down for downloads. Could you please check?

#### Sample URL:
http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-river-jdbc/1.4.4.5/elasticsearch-river-jdbc-1.4.4.5.jar

**Comment by jprante** [comment]
xbib.org was relocated from Germany to France. It is up again now.

Sorry for the inconvenience.

**Comment by rahul-coatue** [comment]
Thanks for resolving it fast
