### ISSUE TITLE
bug:  did not print error log of wrong column name in mysql

### ISSUE THREAD

**Issue by iamtiancaif** [jprante/elasticsearch-jdbc#831]
select id, uid, pay_type, pay_time create_time, money rmb_amount, goods_name, user_ip, status, 
	finish_time, callback_class, business_id, appid, used_channel, reverse_time, description description_pay_request, 
    extern_order_id as extern_order_id_pay_request, callback_info as callback_info_pay_request, id es_sync_id, 
    case isnull(pc.consume_time)    
		when 0 then CONCAT('turnover_history_', year(pay_time), '_', ceil(MONTH(pay_time)/3))    else 'turnover_history'  
    end _index, id as _id 
from tb_to_pay_request_201601 
where id > 0 
limit 10；

there's a wrong column name "pc.consume_time" in sql above, but when i used it to import data nothing appeared in log content.
so the process just kept running without importing anything.

**Comment by jprante** [comment]
MySQL throws  `ERROR 1054 (42S22): Unknown column '...' in 'field list'` in such cases.

 If nothing appeared in the log, there was no error. 

Of course, JDBC importer does not stop just because of erroneous SQL query.

**Comment by iamtiancaif** [comment]
Sorry it's my fault, the error had been print in another file.
Thanks for your reply.
