### ISSUE TITLE
Import using HTTP instead of TCP

### ISSUE THREAD

**Issue by eladtamary** [jprante/elasticsearch-jdbc#834]
Hi, 
Do you have plans to add support for importing data to elasticsearch using HTTP instead of TCP?

Thanks,
Elad

**Comment by jprante** [comment]
Yes. But there is no ETA.

If ES 5.0 will be launched with a HTTP client, I have to check if this is the preferable method.

**Comment by eladtamary** [comment]
Thanks for the quick answer.
