### ISSUE TITLE
错误: 找不到或无法加载主类 org.xbib.tools.Runner

### ISSUE THREAD

**Issue by 23233** [jprante/elasticsearch-jdbc#849]
i download version=2.3.3.0 then go to path bin create my.bat content is 
___

`@echo off

set DIR=%~dp0
set LIB=%DIR%..\lib\*
set BIN=%DIR%..\bin

REM ???
echo {^
    "type" : "jdbc",^
    "jdbc" : {^
        "url" : "jdbc:mysql://127.0.0.1:3306/gg?useSSL=true&useUnicode=true&characterEncoding=utf-8",^
        "user" : "root",^
        "password" : "123",^
        "sql" :  "SELECT * FROM hotel",^
        "treat_binary_as_string" : true,^
        "elasticsearch" : {^
             "cluster" : "elasticsearch",^
             "host" : "localhost",^
             "port" : 9300^
        },^
        "bulk_size" : "100",^
        "index": "gg",^
        "type": "hotel"^
      }^
}^ | "%JAVA_HOME%\bin\java" -cp "%LIB%" -Dlog4j.configurationFile="%BIN%\log4j2.xml" "org.xbib.tools.Runner" "org.xbib.tools.JDBCImporter"

`
``cmd prompt : 错误: 找不到或无法加载主类 org.xbib.tools.Runner``   
``not find org.xbib.tools.Runner``
i need you help~~~

**Comment by jprante** [comment]
Sorry, I am not familiar with Windows.

**Comment by 23233** [comment]
eh~~~~ok ok,i want sure e thing ..
____
**path lib is on this zip ? or on path lib is elasticsearch file  ?**

**I try to version 2.3.1 of the lib folder into the next version 2.3.3 can be executed successfully, but my database table 20 million rows, I suggest*

``java.lang.OutOfMemoryError:Java heap space``

but now im try set path is absolute path ...

good luck~~~~

**Comment by 23233** [comment]
eh~~~ 
___
** if you on the github releases download .zip is not lib folder,so do you want to 

 http://xbib.org/repository/org/xbib/elasticsearch/importer/elasticsearch-jdbc/2.3.1.0/

 download version-dist.zip  the zip have lib folder
 **
