### ISSUE TITLE
How to Update one extra field to to the document

### ISSUE THREAD

**Issue by santublr** [jprante/elasticsearch-jdbc#855]
Hi, 

I've few views created in mysql db like combo, compute etc., I've identfied unique identfier '_id' field. Now each of the views has '_id' column. Each view has some additional columns along with the common columns. 

The combo view content is getting updated without any issue; this is full super set of all '_id's'. The other view's content are not getting updated. They have same '_id' numbers along with some computed columns fields. 

How can I get this done?

export JDBC_IMPORTER_HOME='/opt/elstk/elasticsearch-2.3.3/lib/elasticsearch-jdbc-2.3.1.0'
bin=$JDBC_IMPORTER_HOME/bin
lib=$JDBC_IMPORTER_HOME/lib
echo $bin
echo $lib
echo $inst
echo '{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:mysql://localhost:3306/XXXX",
        "user" : "root",
        "password" : "",
        "sql" : [
                   {
                        "statement" : "SELECT * from combo"
                   },
                   {
                        "statement" : "SELECT * from compute"
                   },
                   {
                        "statement" : "SELECT * from wait"
                   },
                   {
                        "statement" : "SELECT * from compute_wait"
                   },
                   {
                        "statement" : "SELECT * from io_compute"
                   },
                   {
                        "statement" : "SELECT * from compute_io"
                   },
                   {
                        "statement" : "SELECT * from max_io"
                   }
        ],
        "index" : "my_index11",
        "type" : "my_type",
        "versioning" : true,
        "acknowledge" : true,
        "elasticsearch" : {
                "host" : "X.X.X.X",
                "cluster" : "elasticsearch",
                "port" : "9300"
        }

    }
}' | java \
       -cp "${lib}/*" \
       -Dlog4j.configurationFile=${bin}/log4j2.xml \
       org.xbib.tools.Runner \
       org.xbib.tools.JDBCImporter

**Comment by jprante** [comment]
Just create a unique `_id` column by choosing a prefix. 

Example

> select CONCAT('combo_', myidcolumn) as \_id, * from combo 
> select CONCAT('compute_', myidcolumn) as \_id, * from compute
> ...

**Comment by santublr** [comment]
Thanks Jorg for the quick reply and solution. That solved my problem :)
