### ISSUE TITLE
Unable to find elasticsearch-jdbc-2.3.3.1.lib.commons-cli-1.3.1.jar

### ISSUE THREAD

**Issue by hebabil** [jprante/elasticsearch-jdbc#856]
I have downloaded the latest version and when I am trying to run it I have the following message : 

Erreur : impossible de trouver ou charger la classe principale elasticsearch-jdbc-2.3.3.1.lib.commons-cli-1.3.1.jar

Error : unable to find or load the main class elasticsearch-jdbc-2.3.3.1.lib.commons-cli-1.3.1.jar

I have checked the lib directory and this jar file seems to be missing.

Thanks for the assistance

Hakan.

**Comment by jprante** [comment]
You have typographical/syntax errors in the script.

**Comment by hebabil** [comment]
yep, just saw it, thanks for the quick reply and sorry for the dumb question ;-) Although I have another issue now : Exception in thread "main" java.lang.UnsupportedClassVersionError: org/xbib/tools/Runner : Unsupported major.minor version 52.0

$ java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

ES version is 2.3.3.

**Comment by jprante** [comment]
Please use Java 8.

See also https://github.com/jprante/elasticsearch-jdbc/issues/805
