### ISSUE TITLE
Escape double quotes (") character

### ISSUE THREAD

**Issue by eladtamary** [jprante/elasticsearch-jdbc#865]
Hi, 
In case one of the database fields contains double quotes, it is not migrated to elasticsearch.
When I try to escape it in the query (by Oracle replace command), the escaping is done twice (ie \\").
Any idea what can I do to get the correct escaping of double quotes?
Thanks,
Elad

**Comment by jprante** [comment]
Do you mean database field name or value? Can you show your SQL query?

**Comment by eladtamary** [comment]
The problem I had is due to JSON value on one of my column values.
I had to set: "detect_json" : false in order to migrate the JSON as is.
Thanks!
