### ISSUE TITLE
unable to update Part of the document 

### ISSUE THREAD

**Issue by aimhighmp** [jprante/elasticsearch-jdbc#877]
Hi,
   I am unable to update part of the document. i have 8 tables that need to be loaded in to single index. it overwrites document if i use multiple sql commands. 

 Any best way to update part/partial of document?

**Comment by jjbursik** [comment]
I had this same issue and found that by adding the _optype into the SQL it resolves the issue.  Sample query:

`select *, \"update\" as _optype from table`

package org.xbib.elasticsearch.common.util.SinkKeyValueStreamListener -- Line 57 starts the if statement logic for this.

**Comment by aimhighmp** [comment]
Thanks for the response.  Above query is looking for the column update from table.   Below is the error message 
[16:46:36,276][ERROR][importer.jdbc.context.standard][pool-3-thread-1] at fetch: java.sql.SQLSyntaxErrorException: ORA-00904: "update": invalid identifier

java.io.IOException: java.sql.SQLSyntaxErrorException: ORA-00904: "update": invalid identifier

**Comment by jjbursik** [comment]
Check out the mysql-delete-document.sh in bin, you'll see the example I referenced. In my query I'm not referencing a column in my table but creating a generic column within the SQL.

If you're testing in a SQL editor try:

Select 'update' as _optype, * from table

**Comment by aimhighmp** [comment]
Thanks for responding. I am using Oralce Database where i am getting exception on this query.

**Comment by jjbursik** [comment]
Can you provide your SQL?

Running against an Oracle DB I was able to get this to work:

select 'UPDATE' as _optype, owner from DBA_VIEWS

**Comment by aimhighmp** [comment]
Please find response from Oracle DB

SQL> select 'UPDATE' as _optype, owner from DBA_VIEWS;
select 'UPDATE' as _optype, owner from DBA_VIEWS
                   *
ERROR at line 1:
ORA-00911: invalid character
