### ISSUE TITLE
Support for ES 5.x

### ISSUE THREAD

**Issue by nikhil-sahu** [jprante/elasticsearch-jdbc#920]
Please include support for ES 5.x in your updates.

**Comment by nikhil-sahu** [comment]
Bug id #915 already covers this. So closing.

**Comment by bharattomar** [comment]
Thanks Nikhil for adding support for ES 5.x. I was looking at Compatibility Matrix and could not find 5.0 in table. It would be great if you could add this to Compatibility Matrix.

https://github.com/jprante/elasticsearch-jdbc#compatiblity-matrix
