### ISSUE TITLE
About export data from mysql to Elasticsearch

### ISSUE THREAD

**Issue by vfa-cuongnv2** [jprante/elasticsearch-jdbc#928]
I using Elasticsearch JDBC 2.3.4.1. I is newbie, i have 1 bug. This is when export data from mysql to elastich. But i only export 10 rows. 
Anything have help me? Thanks.
I using mysql.
Code in here.
I using fetchsize but has not woking
-------------------------
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
bin=${DIR}/../bin
lib=${DIR}/../lib

echo '
{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:mysql://localhost:3306/dms",
        "user" : "root",
        "password" : "",
        "sql" :  "SELECT LB.leisure_base_id as _id ,LB.leisure_base_id as leisure_base_id, LB.name as leisure_base_name FROM leisure_bases LB",
        "treat_binary_as_string" : true,
		    "index":"leisurebases",
        "type" : "leisurebase",
        "fetchsize" : 100,
        "elasticsearch" : {
             "cluster" : "elasticsearch",
             "host" : "localhost",
             "port" : 9300
        }
      }
}
' | java \
    -cp "${lib}/*" \
    -Dlog4j.configurationFile=${bin}/log4j2.xml \
    org.xbib.tools.Runner \
    org.xbib.tools.JDBCImporter

**Comment by sskmail14** [comment]
What is the error or log  that you are getting out of this code/configuration?
So that it will be easy to figure out what the issue is.

**Comment by jprante** [comment]
How do you know that only 10 rows were exported? How many do you expect? How many are in the table? How many documents are in the index? Please show what commands you use to control the importer result.

**Comment by vfa-cuongnv2** [comment]
@jprante 
When i run script in here. After i run chrome with link : localhost:9200/leisurebases/_search/?pretty.
I see it only show 10 row in database. but in Database of me have > 50 record.
I is newbie, so anything have help me.
Thanks.
@sskmail14 
Hi , i haven't any error. I see it show 10 record in DB of me.

**Comment by vfa-cuongnv2** [comment]
Hi everyone,
I fixed and i will close. Thanks :)

**Comment by sskmail14** [comment]
@vfa-cuongnv2 What is the problem, and how you solved it?

**Comment by vfa-cuongnv2** [comment]
@sskmail14 
Hi Guy, I show all data in brower. Problem in here is limit size show default. after i change size. It show full.
Ex : http://localhost:9200/<index>/_search?pretty=true&q=*:*&size=1000. It will show 1000 record.
Thanks you :)
