### ISSUE TITLE
How could I format a "bigInt" data

### ISSUE THREAD

**Issue by nibnait** [jprante/elasticsearch-jdbc#933]
the data from MySQL database, is a BigInt data, which length is 19. when I transfer it to ES, the last two number become "00". how could I format it into String, before it imported into ES?

中文：MySQL数据库中有一个BigInt型的数据，长度是19位。现在当我用elasticsearch-jdbc将其转移到ES上时，这个数据的最后两位直接变成"00"了。我应该在哪里先把这个数据转换成String，或者用String接收，然后再将其导入到ES上呢？

**Comment by jprante** [comment]
Try to convert `BIGINT` to `DECIMAL`

```
select cast(conv(column,10,10) as decimal(16,2)) from table
```

**Comment by nibnait** [comment]
in the "jdbc" json:
`"sql": "select *, id as _id,restaurant_id as _routing, cast(conv(order_id,10,10) as decimal(20,0)) as orderId from eleme_order_rate",`

but the last two number of order_id is still "00"

![image](https://cloud.githubusercontent.com/assets/16975751/23150471/af3852c0-f82e-11e6-8be8-9e3bd559bcab.png)

but the real order_id is : 1200897761218755709

**Comment by nibnait** [comment]
thank you very much to reply me, but this question is really confused me several days. 
Sincerely look forward to your reply again

**Comment by nibnait** [comment]
Thank you for your ideas. By convert bigInt to char, then I import it into ES, it works.

`select cast(order_id as char(20)) from table`

thanks sincerely
