### ISSUE TITLE
jdk version is confused

### ISSUE THREAD

**Issue by hongjunsu** [jprante/elasticsearch-jdbc#949]
elasticsearch version is 2.3.3 
elasticsearch-jdbc version is 2.3.3.0
this tow jdk1.7 can supported.
but elasticsearch-helper-2.3.3.0.jar  is used jdk1.8  features
see org.xbib.metrics.ExpWeightedMovingAverage
private final LongAdder uncounted = new LongAdder();
what should do for this...

**Comment by jprante** [comment]
Use Java 8.

Java 7 is no longer supported by Oracle.
