### ISSUE TITLE
sql statement issue:when use concat and replace fuction

### ISSUE THREAD

**Issue by scalaLearn** [jprante/elasticsearch-jdbc#958]
when I execute this statement: CONCAT('["',REPLACE(brand_other_names,';','","'),'"]') in NaviCat is fine, but it didn't work in my shell:
"sql" : [ { 
      "statement" : "select a.store_id storeId,a.store_nm storeNm,b.brand_nm brandNm,a.store_id as _id, a.AMAP_LATITUDE as \"location.lat\", a.AMAP_LONGTITUDE as \"location.lon\", CONCAT('[\"',REPLACE(brand_other_names,';','\",\"'),'\"]') as brandOtherNms, from tbl_chmpl_store_inf as a,tbl_chmpl_brand_inf as b where a.brand_id=b.brand_id and a.upd_ts <= ?", 
      "parameter" : [ "$metrics.lastexecutionstart" ]
    }]

Any idea how to make it work,thank you?

**Comment by jprante** [comment]
Use shell escape or put SQL statement in a file and reference it with something like file.sql

**Comment by scalaLearn** [comment]
It works,thank you!
