### ISSUE TITLE
after fetch: no such index 

### ISSUE THREAD

**Issue by sukhesh222** [jprante/elasticsearch-jdbc#967]
Hi, I am using elastic search 2.1.2 and jdbc importer 2.1.1.2. While importing from mysql to elastic search getting this error as:

 [12:51:55,922][ERROR][importer.jdbc.context.standard][pool-3-thread-1] after fetch: no such index
org.elasticsearch.index.IndexNotFoundException: no such index.

I tried almost all solutions available. 
1. Tried using elastic search version 2.3.4 also.
2. In elasticsearch.yml changed as following
 action.auto_create_index: true
 index.mapper.dynamic: false

But still issue is not resolved. Please guide me to solve this.

Here is my code for importing.

bin=/var/www/html/demo/elasticsearch-jdbc-2.3.4.0/bin
lib=/var/www/html/demo/elasticsearch-jdbc-2.3.4.0/lib

echo '{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:mysql://localhost:3306/testDB",
        "user" : "root",
        "password" : "net",
        "sql" : "select * from tbl_test",
"index" : "elasticindex",
"type" : "mytype",
"elasticsearch" : {
         "cluster" : "elasticsearch",
         "host" : "localhost",
         "port" : 9300
      },
    "max_bulk_actions" : 20000,
    "max_concurrent_bulk_requests" : 10,
"index_settings" : {
"index" : {
"number_of_shards" : 3
}
},
 "type_mapping" : {
     "my_index_type": {
     }
  }
    }

}' | java \
       -cp "${lib}/*" \
       -Dlog4j.configurationFile=${bin}/log4j2.xml \
       org.xbib.tools.Runner \
       org.xbib.tools.JDBCImporter

**Comment by mbelatar** [comment]
Any solution ?
