### ISSUE TITLE
support PostgreSQL database？

### ISSUE THREAD

**Issue by AccountGc** [jprante/elasticsearch-jdbc#987]
support PostgreSQL database？

**Comment by wanghc85** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by AccountGc** [comment]
好的

**Comment by AccountGc** [comment]
> 好的

**Comment by wanghc85** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
